### ISSUE TITLE
The message of purchase is shown to the buyer player instead of the seller - 3.9.1-SNAPSHOT (build 54)

### ISSUE THREAD

**Issue by ArtNRG** [ChestShop-authors/ChestShop-3#100]
#### Plugin Version
3.9.1-SNAPSHOT (build 54)
 
#### Plugin Config
https://pastebin.com/raw/qxVaSjbv
 
#### Server Version
Paper-1285 (MC: 1.12.2)
#### Server Log
https://pastebin.com/raw/hAe7aHJu

#### What other plugins are you running?
Plugins (75): ActionBarAPI, afkTerminator, AnimatedNames, AntiInvisPotion, antiraildupe, AreaShop, AuctionHouse, AutoMessage, BungeeTabListPlus, ChatControl, ChestCommands, ChestShop, CHIR, ClearLag, CommandSigns, ConditionalCommands, ConditionalPerms, ConsoleScheduler, CraftBook, CustomPermissionMessages, DeathControl, DeluxeMenus, dynmap, EntityDetection, EpicRename, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard, FreshWilderness, GPAccruals, GriefPrevention, GriefPreventionFlags, HeadDatabase, HolographicDisplays, HopperImprovements, IKD, IPWhitelist, JDynmapGriefPrevention, KickFromClaim, LeaderHeads, LiteBans, LogBlock, LuckPerms, MassiveCore, MassiveLag, MobHunting, Multiverse-Core, Multiverse-NetherPortals, MVdWPlaceholderAPI, MyCommand, MyPet, NoSpawnerChange, Orebfuscator4, PandaWire, ParrotGlue, PerWorldInventory, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, RandomTeleport, React, RedstoneClockDetector, Shopkeepers, SimpleClans, SimpleTrading, Spartan, SuperVanish, TreeAssist, Vault, warptastic, WorldBorder, WorldEdit, WorldGuard

#### What is happening?
The message of purchase is shown to the buyer player instead of the seller.
https://pasteboard.co/H2VpWQp.png
Player Cybertecx13 is selling 64 glass. 
Player Eg0rkka bought it and receive his own message and Cybertecx13's message.

#### What did you expect to happen?
Player Eg0rkka bought it and receive his own message about buying.
Cybertecx13 receive his own message about selling.

Please provide any additional info below
This error is started to appear in a few latest dev builds.

**Comment by Phoenix616** [comment]
Already fixed. See #98.
