### ISSUE TITLE
Potions stack when items is lower than the amount on the sign.

### ISSUE THREAD

**Issue by Skizzles** [ChestShop-authors/ChestShop-3#102]
### Plugin Version
3.9.1-SNAPSHOP (Build 59)
 
### Plugin Config
N/A
 
### Server Version
CraftBukkit version git-Spigot-109b080-ab09b27 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 
### Server Log
N/A no errors show.

### What other plugins are you running?
Essentials, WorldGuard, WorldEdit. Many others that are not apparent to the issue.

### What is happening?
When you buy items from a shop, sometimes the items stack and sometimes they dont.
- The items stack when the chest contains less than the 'amount' stated on the sign (e.g 7 potions in the chest, when the signs 10)
https://gyazo.com/b5a6bf3c5f464992e9bd8b0d432df053
- The items do not stack when the chests contains the same or more than the 'amount' stated on the sign (e.g 10/10+ potions in the chest, when the sign says 10)
https://gyazo.com/da9c7d04a57323c93ccae7ecca64162a

When potions stack you can still drink them. This can be a negative feature.

### What did you expect to happen?
Expect the potions to not stack no matter the amount of items remaining in the chest, due to them stacking that can give an unfair advantage to players as potions are not usually meant to stack.

Please provide any additional info below
The Gyazo links include gifs.

**Comment by Phoenix616** [comment]
Please provide the missing information, especially your config and the server log from when the plugin starts up and when the buying occurs.

**Comment by Skizzles** [comment]
[Config-Logs.zip](https://github.com/ChestShop-authors/ChestShop-3/files/1654270/Config-Logs.zip)
Here is the Config and Log
