### ISSUE TITLE
You dont have enough money.

### ISSUE THREAD

**Issue by Stuperfied** [ChestShop-authors/ChestShop-3#107]
#### Plugin Version
3.9.1 build 61
Also tried 3.9.0 and and an older version.
 

#### Plugin Config
[config.zip](https://github.com/ChestShop-authors/ChestShop-3/files/1669510/config.zip)

#### Server Version
CraftBukkit version git-Spigot-b32c8f8-46226d6 (MC:1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
 

#### Server Log
[latest.zip](https://github.com/ChestShop-authors/ChestShop-3/files/1669517/latest.zip)

#### What other plugins are you running?
chestdrop-1.0-alpha-5.jar
ChestShop-3_Build-61.jar
commandsdispatcher-2.4.12.jar
craftconomy3-master-3.4.0-SNAPSHOT.jar
CustomEnchantments.jar
DiscordSRV-Build-13.5 (1).jar
EnjinMinecraftPlugin.jar
EssentialsSpawn-2.x-SNAPSHOT.jar
EssentialsX-2.0.1.jar
Factions.jar
MassiveCore .jar
mcMMO.jar
Multiverse-Core-2.5.jar
orebfuscator-4.2.1.jar
PAC.jar
PlayerVaults.jar
ProtocolLib.jar
SilkSpawners.jar
SilkSpawnersShopAddon.jar
socket4mc-2.1.3.jar
Vault_1.6.1.jar
ViaVersion-1.2.0.jar
WatchDog.jar
WildTp.jar
worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar
worldguard-6.2.jar

#### What is happening?
I created an Admin Shop sign to enable buying and selling of 1 dirt for 1 unit price as a test.
The sign created successfully.
I left clicked the sign and it stated that I had sold 1 dirt for "." no price, just a dot
I then right clicked and it said that I do not have enough money
I typed /bal and found that I had $1000
Increased balance to $2000 and repeated the steps but nothing seems to fix the issue.
Updated the plugin, updated vault but still nothing.

The log error:
[10:35:35] [Server thread/ERROR]: Could not pass event CurrencyAmountEvent to ChestShop v3.9.1-SNAPSHOT (build 61)

Please provide any additional info below
This server is managed by a server manager of mine, he asked me to take a look. I did notice the errors in the logs and this will most likely be what is causing the issues. I noticed that craftconomy say's its in setup mode, would that cause the issue? On the dev.bukkit chestshop page it say's not to worry about your economy plugin because chestshop uses vault. Anyway, I wanted to get this to you early just in-case it turns out to be an incompatibility issue. The information above is probably also useful insight into how the plugin is being used.

**Comment by Phoenix616** [comment]
> I noticed that craftconomy say's its in setup mode, would that cause the issue?

This is most likely the cause of your issue. ChestShop needs a Vault-compatible economy plugin to work and if that isn't properly setup it cant get any information from it.
