### ISSUE TITLE
Request: disabled worlds

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#110]
Hello,
can you add a configurable option like "disabled worlds"? I wanna disable chestshop creation in certain worlds.

Thank you :smile_cat:

**Comment by Phoenix616** [comment]
This can already be achieved by using permissions as most modern permissions plugins offer the ability to give different permissions in different worlds. So don't grant your player's the permissions to create shops in the worlds you don't want them to (or negate the permissions in these worlds)
