### ISSUE TITLE
Iteminfo too long to fit on sign.

### ISSUE THREAD

**Issue by gelsbern** [ChestShop-authors/ChestShop-3#112]
1.12.2 Spigot Server using dev build from Jenkins.

Not sure if this was intentional, but in the past when you did /iteminfo you got a numeric representation that would fit on a sing, but now when you do /item info, say on chiseled stone brick when you do /iteminfo you get "Smooth Brick Smooth Brick:3"   which doesn't fit on the last line of the sign.   Thx.

**Comment by Phoenix616** [comment]
Generally speaking you should move to using **?** and have the ID autofill but I'l look into having `/iteminfo` display a shortened ID that actually fits on the sign too.

**Comment by gelsbern** [comment]
Thank you.

**Comment by wobby123** [comment]
I also have this issue. The item name is "Diamond Pickaxe#l" and I cannot fit the l. If i put ? it just puts Diamond. Even though it is that pickaxe in the chest

**Comment by Phoenix616** [comment]
Can you please provide the log/screenshot of `/iteminfo` as well as your server and plugin version? `Diamond Pickaxe#l` should fit on a sign (at least when I [test it](https://i.moep.tv/bAruKMB4.png) it does) For actually too long strings it will calculate a short sign name in a way to fit the sign automatically, same goes for using `?` on the sign. That it only displays `Diamond` on the sign would mean that it tries to put a too long name onto it and the rest getting cut off. (Maybe you use a resource pack with a font that is too wide to fit on the sign?)

**Comment by wobby123** [comment]
> Can you please provide the log/screenshot of `/iteminfo` as well as your server and plugin version? `Diamond Pickaxe#l` should fit on a sign (at least when I [test it](https://i.moep.tv/bZoOLH6M.png) it does) For actually too long strings it will calculate a short sign name in a way to fit the sign automatically, same goes for using `?` on the sign. That it only displays `Diamond` on the sign would mean that it tries to put a too long name onto it and the rest getting cut off. (Maybe you use a resource pack with a font that is too wide to fit on the sign?)

It was the texture pack. Didn't think that would affect it. Thank you so much
