### ISSUE TITLE
Development Question

### ISSUE THREAD

**Issue by ryanwoods1706** [ChestShop-authors/ChestShop-3#113]
Trying to hook into ChestShops, is their a way directly for me to check if a chest is a ChestShop?

**Comment by Phoenix616** [comment]
Take a look at the [uBlock](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Utils/uBlock.java) class. It contains utility methods to check if a block is a shop sign or if a chest has a shop sign attached.
