### ISSUE TITLE
Stacking non-stackable items

### ISSUE THREAD

**Issue by baticag** [ChestShop-authors/ChestShop-3#116]
#### Plugin Version
Version 3.9.1-SNAPSHOT (build 62)

#### Plugin Config
https://www.hastebin.com/isekusoweq.vbs
 
#### Server Version
Paper version git-Paper-1353 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

#### What other plugins are you running?
SilkSpawners v5.0

#### What is happening?
Video showing this bug:
https://www.youtube.com/watch?v=R0YAqdX68OE

#### What did you expect to happen?
Items should not be stacked

**Comment by Phoenix616** [comment]
Well, they look to me like they are the same item, why shouldn't they stack?

**Comment by baticag** [comment]
But in configuration of SilkSpawners it is set that spawners do not stack.

# Should spawners be unstackable
spawnersUnstackable: true

Using latest version of SilkSpawners:
https://dev.bukkit.org/projects/silkspawners

**Comment by Phoenix616** [comment]
This is something that plugin should handle. All that ChestShop uses are Bukkit's inventory adding and max stack size querying methods, adding special cases for every single plugin that doesn't properly implement functions is not int he scope of this project.
