### ISSUE TITLE
/iteminfo returning null

### ISSUE THREAD

**Issue by Agazed** [ChestShop-authors/ChestShop-3#117]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.9.1-SNAPSHOT build 67
 
#### Plugin Config
default
 
#### Server Version
PaperSpigot 1.8.8
 
#### Server Log
https://pastebin.com/xXqh7yFd

#### What other plugins are you running?
EssentialsX, Vault, others should not affect, shown in startup log if needed

#### What is happening?
Typing /iteminfo produces a NullPointerException and says internal error.

#### What did you expect to happen?
It to work

Please provide any additional info below
Works fine on build 65

**Comment by Phoenix616** [comment]
You are running a really outdated server version. The latest builds do no longer support these and are in preparation for 1.13. (They are tested on 1.12.2)

**Comment by Agazed** [comment]
Where does it say 1.8.8 is not supported?

**Comment by Phoenix616** [comment]
The [pom.xml](https://github.com/ChestShop-authors/ChestShop-3/blob/master/pom.xml) states 1.12 as the version of the spigot-api that is being used. I've added an additional warning to the development build page now regarding the version that it is being tested on and targeting.
