### ISSUE TITLE
Integrating Chestshop with non-players

### ISSUE THREAD

**Issue by hornta** [ChestShop-authors/ChestShop-3#119]
This is not a bug at all, just a question.

We are making a Company plugin for our server. You will be able to create virtual companies. Just like how you can create virtual Towns with Towny.

We want to make it possible to link shops to a company rather than a player. In fact, we only want to be able to have companies linked to a shop, no players. Is this possible?

I have a plan to fork chestshop and make our own, but I want to know if there are some easier ways to do this.

**Comment by Phoenix616** [comment]
Well theoretically all a company or town would need is a normal economy account that is accessible via Vault and the shops should just work when the name that is in the economy is on the sign.

The only thing that I can think of that is currently preventing this from working is the UUID/namechange handling. It would either require a special functionality for non-player accounts or a way to get an UUID for that virtual account to add that to the users.db.

**Comment by hornta** [comment]
I wish to have only the name of the company on the sign, so having prefixed with b: is not possible for me. Also the economy accounts for the companies are just regular economy accounts prefixed with "company_".

**Comment by Phoenix616** [comment]
The issue is that ChestShop uses the UUID of the players to do all economy transactions. These are only known once a player logs in so you would have to manually add entries for your company to the NameManager with the same UUID that your economy plugin uses in order for it to work without any modification to ChestShop itself.

I still think using bank accounts is the better and more universally usable approach to add support for non-player accounts.

**Comment by hornta** [comment]
The problem is that Vault does not support bank accounts, which is why we can't do that. That is the same reason why Towny also uses "player" economy accounts.
I am going to softdepend on ChestShop and see if I can hook my way into the NameManager.

**Comment by Phoenix616** [comment]
Vault does have support for [bank accounts](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java#L239-L328)?

**Comment by hornta** [comment]
Not all implementations. Otherwise me and plugins like Towny would use it.

**Comment by Phoenix616** [comment]
Well that's really the economy plugin's fault then if it doesn't implement the VaultAPI properly.
