### ISSUE TITLE
Name conflicts?

### ISSUE THREAD

**Issue by hornta** [ChestShop-authors/ChestShop-3#121]
I think I have found a potential bug regarding the creating of shops.
When a shop is created, the name on the sign is stripped to its short name variant, e.g. its first 15 letters.

What if a player named 1234567890123456 (16 characters) creates a shop sign, and then a player named 123456789012345 (15 characters) comes in and creates an other shop sign. Now the shop signs names are identical, but two different players created the signs.

Wouldn't one of the players get rewarded for both the shops now?

**Comment by Phoenix616** [comment]
No, the plugin stores the sign names in the users.db and if a player logs in with a name that might conflict with an existing sign name it will create a new unique one by appending :<id>. In your example it would end up with 1234567890123:0
