### ISSUE TITLE
last update on lwc

### ISSUE THREAD

**Issue by saturnux** [ChestShop-authors/ChestShop-3#126]
on last version on lwc, auto lock is not efficiency. (when you create a shop)
#### What is happening?
[Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!] 

#### What did you expect to happen?
[Explain what you expected to happen after performing the previously described steps]

Please provide any additional info below
[And delete the lines in square brackets]

**Comment by Phoenix616** [comment]
Please provide the missing information that the template asked you to provide, especially the actual versions of your server and plugins and the log and config files. Also as you are talking about efficiency please provided the timings that show that it is inefficient as well!

**Comment by saturnux** [comment]
on lwc (unofficial) here : https://github.com/megoesrawr/LWCEntityLocking

on latest version of lwc, the format of registration's change.

i think you can lock this report, a patch for lwc exist on a fork. 

compatibility should be put in place in the future.
this version of lwc is updated, and probably more compatible with the future version of minecraft.

**Comment by Phoenix616** [comment]
Well if it's a fork then that fork should ensure compatibility with plugins using the upstream API. (as far as I can tell it [should be compatible](https://github.com/megoesrawr/LWCEntityLocking/blame/master/src/com/griefcraft/sql/PhysDB.java#L1165) though?) I don't think adding support for that specific fork is possible seeing as what a general mess it seems to be: No proper changelog, no commit messages and a very hacky entity protection implementation.

Regarding the future of the original LWC: I will probably keep [my fork](https://github.com/Minebench/LWC/) updated, also [dmulloy2's fork](https://github.com/dmulloy2/LWC) should be pretty up to date too and includes an entity protection working similar to the one you mentioned.

But let's see what the future really brings as 1.13 will change a bunch of stuff related to Materials and their IDs and we'll see how the different versions handle that.
