### ISSUE TITLE
Fermented Spider Eye ID is giving normal Spider eye

### ISSUE THREAD

**Issue by Zoneman1972** [ChestShop-authors/ChestShop-3#128]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version

 Version 3.9.1 (build 72)
#### Plugin Config
Not necessary
 
#### Server Version
This server is running CraftBukkit version git-Spigot-2086bb0-21d5f75 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 Latest

#### What is happening?

When you try and buy a Fermented Spider Eye with that ID, you get a normal Spider Eye instead.

http://prntscr.com/jb83fw

#### What did you expect to happen?

Expect to get a Fermented Spider Eye like it used to do before the most recent update

Please provide any additional info below

This was all working fine up until the most recent update. Also some of the Mob spawners id's have changed and we needed to recreate a lot of the signs

**Comment by Phoenix616** [comment]
I suggest using the IDs given by `/iteminfo`, these are guaranteed to give the correct item (at least with the version that they were generated with) as that includes a check if the string results in the same item as the input.

Interesting though that your string would result in a spider eye. It seems to ignore the first part, gonna look into that but that's not really a priority seeing as `/iteminfo` generates a working ID.

**Comment by Zoneman1972** [comment]
Thanks for the reply but it is actually from the /iteminfo command. 

Even though you enter ferm_spider_eye you still get a normal spider eye.

**Comment by Phoenix616** [comment]
I cannot reproduce this issue with Ferm Spider Eye on the latest build. If you aren't using that then please try it.

**Comment by Phoenix616** [comment]
I assume this is fixed.

**Comment by Zoneman1972** [comment]
Sorry mate. I no longer use ChestShop since the 1.13 update.
