### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [ChestShop-authors/ChestShop-3#130]
I'm the developer of the [Reserve Spigot Plugin](https://www.spigotmc.org/resources/reserve.50739/), a Vault-like plugin that aims to bring a more modern version of Vault to the Bukkit ecosystem. The reason behind opening this ticket is to see if ChestShop would add Reserve support as ultimately the best way to gain traction is by getting support from various plugin developers, currently Reserve is supported by my economy plugin, and Towny, but I'm hoping to get it implemented in many of the popular economy-related plugins that are commonly used by server owners.

Thanks,
   creatorfromhell

**Comment by Phoenix616** [comment]
I'm always open for suggestions (especially in the form of pull requests) but I'm not sure yet how this plugin would benefit from yours? Wouldn't all economy plugins basically have to already support Vault as it's the quasi standard for economy integration?

**Comment by creatorfromhell** [comment]
I'll make a PR on this after I release my economy plugin with Reserve support.

**Comment by Phoenix616** [comment]
Implemented in 8ae72e580341217e85af533f1fafeb758c3db07b
