### ISSUE TITLE
Admin Shop Sign not working (Enchantment book)

### ISSUE THREAD

**Issue by leejosepho** [ChestShop-authors/ChestShop-3#135]
#### Plugin Version: 3.9.1 (Build 72)
```
ADMIN_SHOP_NAME: "BookShop"
#First line of your Admin Shop's sign should look like this:
SERVER_ECONOMY_ACCOUNT: ""
#The economy account which Admin Shops should use and to which all taxes will go
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account. (100 = 100 percent)
SERVER_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SHOP_CREATION_PRICE: 0.0
#Amount of money player must pay to create a shop
SHOP_REFUND_PRICE: 0.0
#How much money do you get back when destroying a sign?

WORLDGUARD_INTEGRATION: false
WORLDGUARD_USE_FLAG: false
WORLDGUARD_USE_PROTECTION: false

AUTHME_HOOK: true
AUTHME_ALLOW_UNREGISTERED: false
```
note: '/rg flag spawnshop allow-shop allow' is set
 
#### Server Version: git-Paper-1425 12,2,2

CoreProtect, WorldGuard, Vault, EssentialsX Eco

#### What is happening?

Admin Shop Sign not working:
```
BookShop
1
B 1
Enchante Book#1
```

1. What config edits do I need?
2. How can I change the name of the book if the sign can be made to work?

![bookshop 01](https://user-images.githubusercontent.com/22735096/40882357-f436d3d4-66a4-11e8-92aa-873cc6ad863b.png)

**Comment by Phoenix616** [comment]
Please test if this is still an issue with the latest [development build](https://ci.minebench.de/view/Various/job/ChestShop-3/) and make sure that it isn't inside the spawn protection.

If still doesn't work then please describe what you mean with "doesn't work" (does it at least show the shop created dialog?) and provide your log file.

**Comment by leejosepho** [comment]
>> Please...make sure that it isn't inside the spawn protection.

The sign works for someone other than myself outside of the spawn region.  And so:

1. How can I make the sign work inside the spawn region?
2. How can I make it work for myself exactly as for any other player?
note: This is a server (admin) shop and I do *not* want the income.
3. How can I change 'Enchante Book##s' to the names of the Enchantment books?

**Comment by Phoenix616** [comment]
I meant the vanilla spawn protection where only ops can build/use signs, not a region. If it works for someone else then that's not the issue. Make sure that you aren't in creative mode or have enable usage of creative mode in the config. (It's a setting that you conveniently left out when posting your config)

For the item ID: You can't change that, that's the unique ID of that item. Listing any more information does not fit on the sign. The command `/iteminfo <id>` should display that info though.

**Comment by leejosepho** [comment]
>> Make sure that you aren't in creative mode or have enable usage of creative mode in the config.
Ah, I had missed that as the problem.

>> For the item ID: You can't change that, that's the unique ID of that item. 
>> Listing any more information does not fit on the sign.

I do not want to list more information, I want/need to replace the default information being generated by the plugin.

>> The command /iteminfo <id> should display that info...

Yes, and it is meaningless.  I want/need to show players what is for sale without my having to use twice as many signs as should be needed.

![bookshop 02](https://user-images.githubusercontent.com/22735096/40887325-d28c9f94-670c-11e8-892c-00d3b39c26a0.png)

**Comment by leejosepho** [comment]
>> I added info for enchanted books to the /iteminfo command for now.

Is that something new you have just done and I should try a new jar?

>> I have been wanting to add the ability to change the ID before the unique #id for a while now so that might get implemented eventually.

I understand, and in the meantime:

I have performed the /iteminfo command on each Minecraft enchantment item, and those 87 entries in my ChestShop database are all identical except for the last four (4) characters of each.  I do not know how that could be possible since 'Enchantment Table' and 'Bottle O' Enchanting' are the first two, so where are the IDs for the signs actually being stored?  Point me in a right direction and I will edit the entries or whatever manually so I can accomplish what I am trying to do.

**Comment by Phoenix616** [comment]
> Is that something new you have just done and I should try a new jar?

Yes, build 79 will have that.

> I have performed the /iteminfo command on each Minecraft enchantment item, and those 87 entries in my ChestShop database are all identical except for the last four (4) characters of each. I do not know how that could be possible since 'Enchantment Table' and 'Bottle O' Enchanting' are the first two, so where are the IDs for the signs actually being stored? Point me in a right direction and I will edit the entries or whatever manually so I can accomplish what I am trying to do.

You can't. It directly uses Bukkit's [Material](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) names from the sign line. The ID behind the # is currently just used for the metadata storage. Maybe in the future it will also get the Material from the #ID directly allowing changing of the string before it but currently that's not really possible as it only really stores the metadata, not the item's damage/data value.

**Comment by leejosepho** [comment]
>>  I added info for enchanted books to the /iteminfo command for now.
>> ...build 79 will have that.

Excellent!

![chestshop 03](https://user-images.githubusercontent.com/22735096/40891669-b2b6da66-674f-11e8-9f1c-7f8b3c5bfea0.png)


Many thanks.
