### ISSUE TITLE
Question: Item Blacklist

### ISSUE THREAD

**Issue by Castiella** [ChestShop-authors/ChestShop-3#136]
People keeo trying to sell "air" in shops, and its causing crashes. I was wondering if there was an item blacklist we could use to block people from selling air?

**Comment by Phoenix616** [comment]
There are permissions to (dis)allow buying, selling and creating shops for all items. I will look into that issue though, selling air isn't really intended. If you could provide the information requested by the issue template like the log it would definitely help. ;)

**Comment by Affixes** [comment]
@Phoenix616 Has there been any progress regarding this issue? We are always experiencing crashes with players who create "Air" item shops.

See: https://files.connected.sh/oysqnbdnb3.png

**Comment by Phoenix616** [comment]
As already stated: You can use permissions to blacklist certain items.

And for the issues with air itself I haven't gotten any information on what's actually wrong with it (log file, server version, plugin version, basically the stuff requested in the issue template that was ignored) and I was not able to reproduce it on the latest version.
