### ISSUE TITLE
Deleting all shop sign from world

### ISSUE THREAD

**Issue by FerhatAYDN** [ChestShop-authors/ChestShop-3#137]
Plugin Version

[The full plugin version that you are running from /version ChestShop]

 3.8.12

 

Plugin Config

[The full config.yml file of ChestShop]

https://hastebin.com/vowiqanewo.vbs

 

 

What is happening?

My essentials user.db was deleted so when players buy something it creates lag and this error in console https://hastebin.com/lomigozeyo.vbs. So i want to delete all sign shop from world. I tried worldedit, fawe and mcedit but didn't work.

**Comment by Phoenix616** [comment]
Besides the fact that you are using an outdated plugin version and probably server too: ChestShop itself does not contain the ability to delete shops. You could however do that with a custom plugin that listens on the sign interaction or just replace the signs with other plugins/programs like WorldEdit or MCEdit. I suggest however to get your economy sorted out and maybe use an economy plugin that actually works correctly (or get the one that you are using fixed)
