### ISSUE TITLE
(suggestion) Items banned

### ISSUE THREAD

**Issue by felipeleite5w** [ChestShop-authors/ChestShop-3#144]
it would be nice if you create a item blacklist, because there are some items in mods that have some type of bug, so people could choose what items will be allowed to be sold

**Comment by Phoenix616** [comment]
This already exists through [permissions](https://dev.bukkit.org/projects/chestshop/pages/permission-nodes). All sell/buy/shop-creation permissions can be negated for certain item types.

**Comment by felipeleite5w** [comment]
I didnt found that, could you post the permission to block an item to be sold or bought

**Comment by Phoenix616** [comment]
I did in my comment, click the "permissions"-link.

**Comment by felipeleite5w** [comment]
ok, but I want block a certain item to be sold, and there just have like ''lets you buy or sell only specific items from shops''

**Comment by felipeleite5w** [comment]
I dont want to allow a certain item. I want to block

**Comment by Phoenix616** [comment]
Just remove/negate the permission? Negating is usually done by adding a `-` to the front of the permission but that depends on your permission plugin.

**Comment by felipeleite5w** [comment]
Ok, THANKS A LOT!

**Comment by felipeleite5w** [comment]
So if I put like that - -ChestShop.shop.buy.2755
                               - -ChestShop.shop.buy.2755 
Players will not buy or sell the item 2755 ?

**Comment by felipeleite5w** [comment]
And they would buy or sell another items ?

**Comment by Phoenix616** [comment]
If you are using the latest build then you should be u sing the string ID and not the number. Also that permission would prevent players from buying items with that ID from a shop.
