### ISSUE TITLE
Chestshop not support ÁáÉéÍíÓóÖöŐőÚúÜüŰű playername

### ISSUE THREAD

**Issue by andris155** [ChestShop-authors/ChestShop-3#145]
#### Plugin Version
ChestShop version 3.9.2-SNAPSHOT (build 83)
 
#### Plugin Config
https://pastebin.com/vyGh6y4f
 
#### Server Version
This server is running Paper version git-Paper-1468 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 
#### Server Log
I send if need.

#### What other plugins are you running?
`Plugins (81): 2048, AdditionsAPI, AnvilRestrict, AreaShop, Battleship, BottledExp, ChangeSkin, ChatControl, ChestShop, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CrazyAuctions, CreativeNbtControl, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, FastAsyncVoxelSniper, FastAsyncWorldEdit, GameBox, GemCrush, Heads, JukeBox, Kredites, LockettePro, LogicPuzzles, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MineMarketAPI, Minesweeper, MobArena, MobHeads, MobMerge, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, myZone, NametagEdit, NoCheatPlus, NoSpawnerChange, OpenInv, OpenTerrainGenerator, Paintball, PickupSpawners, PlayerWarp, PlotSquared, PlugMan, ProtocolLib, PvPManager, RandomTeleport, redclockdetector, RedstoneClockDetector, RestrictedCreative, Shopkeepers, SignEdit, Stats, SuperLuckyBlock-Pro, SurvivalGames, TimeIsMoney, TitleManager, TreasureChest, VanillaAdditions, Vault, Vehicles, Votifier, VotingPlugin, VoxelSniper, WhacAMole, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, YouTubeBridge
`
#### What is happening?
Not workd shop

#### What did you expect to happen?
Work shop

Please provide any additional info below
![2018-07-10_16 07 03](https://user-images.githubusercontent.com/8324198/42515137-58caaab8-845b-11e8-8ac0-f81269f2421b.png)

**Comment by Phoenix616** [comment]
These are not valid Minecraft usernames so it makes sens that they don't work. If you want to use that name for the admin shop you will have to set the admin shop name in the config to that value too.

**Comment by andris155** [comment]
This is a valid Minecraft usernames on cracked (offline) server.

**Comment by Phoenix616** [comment]
You will run into lots of similar issues if you allow names like this. I can't spot anything obvious why it wouldn't work though but I personally have no interest in doing any work to support offline-mode servers. Feel free to write a fix (or make someone do that) and PR it in.
