### ISSUE TITLE
Prevent LWC spam when using a shop.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#152]
Is there / or can there be some sort of LWC integration + config option to prevent chest shop from shooting the "this chest is private" message every time a user use's the shop?

Our settings are as such:
```
#Do you want to protect shop chests with LWC?
PROTECT_CHEST_WITH_LWC: true
#Do you want to protect shop signs with LWC?
PROTECT_SIGN_WITH_LWC: true
#Should the chest's LWC protection be removed once the shop sign is destroyed? 
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
```

However we continue to get reports like this:
https://ecocitycraft.com/forum/threads/skyblock-server-suggestion-reduce-spam-for-sell-chests.177259/

Would be nice if you can add this to chest shop so LWC notification don't shoot for chestshop.

**Comment by Phoenix616** [comment]
I really doubt that LWC's API supports selectively turning of these notifications but I will look into whether or not there is a workaround, maybe there is a way to get ChestShop to cancel the event before it reaches LWC or something.

A quick workaround to stop it for now would be to disable LWC's notifications for normal players (something I do on my server) and tell them to use /cinfo if they want that information.

**Comment by andrewkm** [comment]
Alright thank you @Phoenix616 
Let me know what you figure out :) and if it's possible on your end.

**Comment by Phoenix616** [comment]
Unfortunately there doesn't seem to be a way to stop that. LWC doesn't fire any event when it blocks an interaction nor does it respect the cancel state of the sign interaction. For me to be able to hide this message LWC would need to do one of those. ChestShop already cancels the PlayerInteractEvent when a shop is found so all LWC would really need to do is respect that and not check for protections/send a message in that case.
