### ISSUE TITLE
/Iteminfo doesn't show item ID anymore?

### ISSUE THREAD

**Issue by HotelMakar** [ChestShop-authors/ChestShop-3#155]
#### Plugin Version
3.9.2-1.8.8-hotfix (build 82)

**Comment by Phoenix616** [comment]
Can you provide a quick screenshot of what you mean? (or the log if there are any errors in the console) If you have 1.8.8 already running that's faster than me trying to get it working again...

**Comment by HotelMakar** [comment]
Sorry for very very very late reply.
heres a screenshot https://gyazo.com/f68fde5f6de40aae102016c075c7e36e
last time it shows like ID: 4
now it doesn't?

**Comment by Phoenix616** [comment]
Numeric IDs have been deprecated for a long time. While you can still use them on server versions that support them it is advised to use the string names of the items instead. (The command will always output a name that will fit on a sign, I would suggest to just use the autocomplete functionality though)
