### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#156]
Version, error, all here: https://sentry.stylecraft.cz/share/issue/6fc7d2783f2542ad8b458a8cd3093250/

Server 1.12.2

**Comment by Phoenix616** [comment]
Please test if this issue occurs on the 3.9.2 release version (which is the [last 1.12.2 build 86](https://ci.minebench.de/job/ChestShop-3/86/)).

**Comment by Rukes** [comment]
To be honest I dont know what fired this error, sentry just reported it to me. I'll try and if it occurs again I will report it.

Thank you
