### ISSUE TITLE
Log world coordinates on every shop message.

### ISSUE THREAD

**Issue by RedNifre** [ChestShop-authors/ChestShop-3#159]
(I'm just playing on the server so I don't know any version of anything)

Please log the chest coordinates on every log message. Right now, the logs are very chaotic:

"Full": player, item, coordinates
"Bought/Sold": player, item, price
"Out of stock": item

I'm running something like a stock exchange where I have many chests for the same item but with different prices and the "Out of stock" message doesn't tell me which one of the many chests with that item is empty, so I can't update the connected twitter account properly.

Adding world coordinates to "out of stock" or all chest related log messages would help me immensely. If you want to see what I'm doing you can look at the sw_boerse account on Twitter.

**Comment by Phoenix616** [comment]
The [full](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Configuration/Messages.java#L33)/[out](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Configuration/Messages.java#L37) of stock messages already include these information. The buying/selling doesn't though.

**Comment by Phoenix616** [comment]
Well what message is used depends on the plugin config. It seems to already use the version that included the coordinates for the full/empty shops, for the others the plugin needs to be updated to the latest version and the message config to be modified with the coordinates.

**Comment by Phoenix616** [comment]
Yes it should work  with 3.9.1 and if not then the messages config doesn't include it for that message.

**Comment by RedNifre** [comment]
Yeah, it turned out that they were using a recent version, but never updated the plugin config so it was still from an old one. Thanks for your help, this issue is resolved from my side now, too ;)
