### ISSUE TITLE
Startup error: BlockData class

### ISSUE THREAD

**Issue by Rukes** [ChestShop-authors/ChestShop-3#160]
Error + plugin version on [this](http://prntscr.com/ko0snt) screen, server version [here](http://prntscr.com/ko0sxd).

**Comment by Phoenix616** [comment]
You are correct, build after #86 on the main dev build page are for 1.13 which is what's causing this error. There is a separate job for 1.12 backports now though: https://ci.minebench.de/job/ChestShop-3-1.12/ ;)

**Comment by Rukes** [comment]
Thanks.
