### ISSUE TITLE
Player not found!

### ISSUE THREAD

**Issue by BBoyJD10** [ChestShop-authors/ChestShop-3#171]
Complete default configs,

Players cant buy or sell with shops or admin shop error:

Player not found!

**Comment by NullCase** [comment]
Same problem. It seems like something changed today. Either on Multicraft or UUID related.

**Comment by lhdev** [comment]
FYI, multicraft has nothing to do with any plugin operation or minecraft functionality.  It would be at the server level, Bukkit, Spigot, Paper, Bungee or plugin issues.

I can confirm this issue exists on my server as well.  ChestShop has not been updated recently.
My guess would be something with spigot or Paper or the minecraft uuid servers or whatever controls user lookups.

This server is running Paper version git-Paper-325 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by NullCase** [comment]
@BBoyJD10 did your server also become inaccessable earlier today? Maybe some odd behavior starting around 1:40 EST, 3:40 EST, 9:20 EST?

For myself, multicraft stopped sending messages to the console at 1:40. My server logs are missing data between 3:40 and 9:20. And the server crashed at 9:20 (all times in EST).

**Comment by lhdev** [comment]
My server is logging and multicraft is fine.  Also Multicraft doesn't update itself unless you're on a shared server where you don't manage your multicraft install.

**Comment by NullCase** [comment]
Sorry, it seems like you're saying my crash problem is unrelated. That might be true.

I did also update Paper to version 327 after the crash. Perhaps the most recent versions of Paper are causing this?

**Comment by BBoyJD10** [comment]
Dont use multicraft so dont have that issue.

**Comment by lhdev** [comment]
I'm saying multicraft issues are 100% unrelated to anything with regards to chest shop.
Your crash is hard to say, share your crash report and I'll help you decipher it.  Aside from that, we're all seeing this ChestShop issue which I don't believe is ChestShop related.

**Comment by NullCase** [comment]
We're all seeing this ChestShop issue.

@BBoyJD10 do you also use a very recent version of Paper 1.13?

**Comment by NullCase** [comment]
https://github.com/PaperMC/Paper/issues/1525

**Comment by Phoenix616** [comment]
Is someone able to confirm that this is fixed in Paper 1.13 builds above 330?

**Comment by NullCase** [comment]
confirmed.

**Comment by Phoenix616** [comment]
Thank you!

**Comment by tivyhosting** [comment]
This same issue exists in Papers latest build for 1.12.2, is it possible to back port the fix?

**Comment by Phoenix616** [comment]
Then you are having a different issue, this was not a problem before 1.13.
Please open a new ticket and provide the requested information.
