### ISSUE TITLE
Plugin get disabled on startup - 1.13.1

### ISSUE THREAD

**Issue by TheoRetisch1** [ChestShop-authors/ChestShop-3#172]
Hejo,
running the latest development build on a 1.13.1 server it get disabled on startup. The following error occurs in the log: https://pastebin.com/mcW5D3vs

ChestShop: ChestShop v3.9.3-SNAPSHOT (build 101)
Paper: 1.13.1 #346

**Comment by TheoRetisch1** [comment]
Sorry: Worldguard version 7.0.0 -Snapshot;7e0ff24

**Comment by TheoRetisch1** [comment]
You are right it is related to worldguard. If I don't load worldguard chestshop works perfectly fine, wtf. The normal worldguard releases from here http://builds.enginehub.org/job/worldguard/last-successful?branch=master don't work for me. Because of the FAWE dependencies I downloaded worldguard from here: https://empcraft.com/fawe/download/

**Comment by Phoenix616** [comment]
Please test if that happens with the normal WorldGuard too, if it doesn't then that is an issue that your custom version needs to solve.

**Comment by TheoRetisch1** [comment]
It is an issue that the FAWE author Empire needs to fix -> it doesn't happens with the official Worldguard version. Thnak you for your help and sorry for the inconvenience, seems like stuff is getting more complicated due to all the dependencies xD.
