### ISSUE TITLE
plugin error 1.13.1

### ISSUE THREAD

**Issue by Halfhand1** [ChestShop-authors/ChestShop-3#173]
Hi,

I've been looking for a playershop plugin for a while and just started using this plugin and got this error.

error: https://pastebin.com/jccqywAE
server version: 1.13.1

Im not sure what it means, it seems to pop up whenever someone buys an item for a chestshop

 
Thanks alot

**Comment by Phoenix616** [comment]
Please use the latest build for 1.13, you are still on an 1.12 build.
