### ISSUE TITLE
Admins can not create a shop for other users

### ISSUE THREAD

**Issue by Bloodrayne1995** [ChestShop-authors/ChestShop-3#176]
#### Plugin Version
ChestShop version 3.9.3-SNAPSHOT (build 102)
A chest shop for economy plugins.
Authors: Acrobot and (LINK to Contributor)
 
#### Plugin Config
[Pastebin](https://pastebin.com/HN6Fkyn9)
 
#### Server Version
This Server is running Paper version git-Paper-388 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 
#### Server Log
[Pastebin](https://pastebin.com/NVtHMYTA)

#### What other plugins are you running?
 AreaShop*, AsyncWorldEdit, AsyncWorldEditInjector, BungeeTabListPlus*, ChestShop, Citizens, ColoredTags*, CommandBlockBridge*, CompatNoCheatPlus*, CoreProtect, CraftBook, CustomListenerCommands*, DelayedCommand*, EditableSign*, Eobooks*, EonaCore*, EonaRegion*, EonaSpawnerListe, Essentials*, EssentialsChat*, EssentialsGeoIP*, EssentialsSpawn*, FreeBungeeChat*, HeadDatabase*, HolographicDisplays, iConomyRecreation*, Jobs, JumpBlocks*, LagMonitor*, LuckPerms*, LWC, Multiverse-Core*, Multiverse-NetherPortals*, MultiWorldMoney*, NoCheatPlus, PaidSwitch*, PetBlocks*, ProtocolLib*, ServerSigns*, ShowScoreboardValue*, SimpleVoteListener*, Stables*, TouchscreenHolograms*, Vault*, Votifier*, WorldBorder, WorldEdit, WorldGuard

#### What is happening?
A User with the permission Chestshop.Admin want to create a Chestshop for a another user. 
Instead of creating the Chestshop for the particular user, it creates a Chestshop of the creator.

#### What did you expect to happen?
I expected to create a shop for another user.

#### Additional informations
I did some investigations in the source code. 
The Class [NameChecker](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/PreShopCreation/NameChecker.java) on line 25 checks with help of NameManager.canUseName whether the executor can use another name.

The Class [NameManager](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/UUIDs/NameManager.java) checks on line 303 whether the executor has the permission "ChestShop.Admin".

This is done by Permission.otherName() in class [Permission](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Permission.java) on line 50. 
I think there is the problem. If the executor has the Permission "ChestShop.admin" it returns false.

I checked this presumption. I use LuckPerms. If I set the permission "Chestshop.admin" to false, I can create Shops for other users.

I don`t know if this is a bug. But I would be thankful, if you can check this behavior.

Greetings 
EONA Bloodrayne

**Comment by Phoenix616** [comment]
That's really strange that it would return false there if the user has the admin permission... I think the method was used for a check before where that was important but isn't anymore, interesting that this was never noticed in the last 7 years.

**Comment by Bloodrayne1995** [comment]
So will it be changed or not?

**Comment by Bloodrayne1995** [comment]
nvm, im to dumb to read
