### ISSUE TITLE
OP opens all shops when ALLOW_SIGN_CHEST_OPEN: true

### ISSUE THREAD

**Issue by NullCase** [ChestShop-authors/ChestShop-3#178]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
Chestshop v. 3.9.3-SNAPSHOT (build 104)
 
#### Plugin Config
ALLOW_SIGN_CHEST_OPEN: true
 
#### Server Version
Paper 1.13.2 build 392 (released ~now)
 
#### Server Log
[The full latest.log file]

#### What other plugins are you running?
[List of your plugins, ideally with the version] 

#### What is happening?
Be OP. Set ALLOW_SIGN_CHEST_OPEN: true. Right click another players shop sign. Opens.
Be OP. Set ALLOW_SIGN_CHEST_OPEN: false. Right click again. Doesn't open.

#### What did you expect to happen?
Expected right click to purchase from the other players chest.

Please provide any additional info below

**Comment by Phoenix616** [comment]
Yes, that commit is the reason for this change in behaviour. Previously the check if someone had access to a shop ignored the admin permission which is now fixed and they can now access and create other shops properly. If you don't want people to have that ability don't give them the admin permission. It's granted to ops by default to allow usage without a separate permissions plugin so you will hale to negate it if you don't want ops to have access to that functionality.

**Comment by NullCase** [comment]
Hi @Phoenix616 thanks for the quick reply.

I would have to negate it. OK, that makes sense.

How do I do that, in the case of OP?

**Comment by andrewkm** [comment]
@NullCase stop using OP and set permissions properly through a permissions system like LuckPerms.
