### ISSUE TITLE
chestshop.admin permission issues persist

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#185]
@Phoenix616 
Configuration: https://pastebin.com/vB7wzyvJ

Our staff have the following perms:
chestshop.admin
chestshop.mod

And they inherit the following permissions from regular players:
chestshop.shop.*
chestshop.toggle

Staff cannot buy/sell from chests, not unless we remove the chestshop.admin permission.
I believe you aren't understanding the exact issue. Please contact me via Discord so I can explain and show this to you on our test machine.

It's simply not working correctly.

Making new ticket as your closing all the others without confirmation of a fix.

Please explain how to allow those with chestshop.admin permission to purchase/sell from/to shops, while still being able to open them to examine contents.

**Comment by andrewkm** [comment]
Nvm, going to fork and fix on my end.

**Comment by Phoenix616** [comment]
You have `IGNORE_ACCESS_PERMS` set to `true` in your config. You need to disable this if you don't want the shops to ignore players that have access to it ;)

**Comment by andrewkm** [comment]
I’ve already tried this and it does not fix the exact outlined situation above.

Permissions need to be redone within the plugin to be honest. Got someone working on it, no worries.

On Nov 19, 2018, at 3:56 PM, Max Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


You have IGNORE_ACCESS_PERMS set to true in your config. You need to disable this if you don't want the shops to ignore players that have access to it ;)

**Comment by andrewkm** [comment]
Are you also able to open the shop and edit the contents?

On Nov 19, 2018, at 4:26 PM, Max Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Well it works when I test it: Even with the ChestShop.admin permission or the ChestShop.name.* permission set I am able to buy and sell to a shop of another player if the config option is set to false.

**Comment by andrewkm** [comment]
Ok, the entire permissions logic and setup is just completely off. We have a mock setup done now that’s working as it should, going to just rewrite it all on our end. It’s all good.

Thanks for trying to help.

**Comment by Phoenix616** [comment]
> Are you also able to open the shop and edit the contents?

Yes
