### ISSUE TITLE
Could not pass event BuildPermissionEvent

### ISSUE THREAD

**Issue by seema84** [ChestShop-authors/ChestShop-3#189]
https://pastebin.com/mkZLsJMm

Spigot (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
ChestShop's version is: 3.9.3-SNAPSHOT (build 109)

**Comment by Phoenix616** [comment]
`Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/math/Vector3;`

You are using an outdated test-build of WorldEdit, please update to at least build 3930.
