### ISSUE TITLE
1.13.2 ID

### ISSUE THREAD

**Issue by comonier** [ChestShop-authors/ChestShop-3#190]
| Light Gray Concrete | minecraft:light_gray_concrete | 251:8 | minecraft:concrete

Trying to create an AdminShop to sell colored concrete to the players I could not use the sample id number: 251:15 for black concrete, but I was able to use the black_concrete name code worked. But how can I sell clear light gray that has a very big name? and it does not fit on the board: light_gray_concrete?

Since the chestshop recognizes almost no id by number. Or did the numbers change on 1.13.2?

**Comment by comonier** [comment]
nvm it accepted uncomplete code, light_gray_concr  (and done)

**Comment by Phoenix616** [comment]
Yes, it uses short forms of the string IDs as 1.13 no longer supports numeric IDs. The `/iteminfo` command will create a short form that is guaranteed to be unique. (at least for the version it was created with)
