### ISSUE TITLE
Problems with converting shop signs 1.12.2 -> 1.13.2

### ISSUE THREAD

**Issue by TheoRetisch1** [ChestShop-authors/ChestShop-3#192]
Hejo,

Many sales signs do not work after an update from version 1.12.2 to version 1.13.2. For example, you can no longer buy grilled pork, colored glass and many enchanted weapons and books. The sales signs for other items, like stone or lapis blocks work fine. If you rebuild the signs on the 1.13.2 version you can buy and sell everything.
I don't know how you designed the conversion process from 1.12.2 signs to 1.13.2 signs, but it only works partially. There are no errors in the log. It would be wonderful if all signs would work after an update. Otherwise we would have to ask quite a few players to rewrite their shop signs. I appreciate any help you can provide!

ChestShop: 3.9.3-SNAPSHOT build109
Paper 1.13.2 - 493

**Comment by Phoenix616** [comment]
I had hoped that stuff like this wouldn't happen with how the data values were put onto the signs in previous versions but I guess there are some items that had no data values that got unnecessarily renamed. The current "process" just banked on the fact that most materials stayed the same or could still be parsed, there is no more conversion than that as there is no central storage of shop information and everything would need to be done directly on shop interaction.

I guess the solution for this would be to find the items that don't work when the shop was created on 1.12 and fall back to them when no item can be found with the 1.13 parsing.

**Comment by TheoRetisch1** [comment]
Hejo, thank you for your quick evaluation! I'm also not very impressed by all the bugs of version 1.13 in general.  That sounds like a good solution. Can you find the corresponding item with a check or do you need more information from me?

**Comment by Phoenix616** [comment]
I just tested it and it works just fine, even with damage values. You need to use at least build 111 of ChestShop and install the [ChestShop-LegacyIds module](https://github.com/ChestShop-authors/ChestShop-LegacyIds) though.

**Comment by TheoRetisch1** [comment]
Thanks for the support! I didn't installed the legacy module correctly. Now almost all signs are converted correctly, that's very helpful! Thank you :). However some exceptions still don't work. For example redwood leaves, redwood saplings, stone:5, stone:1, stone:3 or dark oak door item.

Starup log: https://pastebin.com/TrnaYW6K
