### ISSUE TITLE
[Request] Price Limits

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShop-3#193]
#### Plugin Version
3.9.3-SNAPSHOT (build 109)

#### Plugin Config
locale.yml:
```
INVALID_SHOP_DETECTED: "The shop cannot be used!"
```
#### Server Version
1.13.2

#### What is happening?
If Price Limits are set, and the player is trying to make a buy/sell chest that exceeds the price limits, a message appears.
`[Shop] The shop cannot be used!`
The reason is too vague and is not understood by players.
Of course, I can change it to something more appropriate, but it doesn't help very much.

#### What did you expect to happen?
I would like to suggest something more informative like:
`PriceLimitExceeds: "The shop was not created because the price exceeds the %min/max% of %price%"`

Would that be possible?

**Comment by Phoenix616** [comment]
I added different error messages for the limits in that commit. Unfortunately it's not easily possible to include the actual limits with how shop creation error messages are currently handled which is why I'll keep this issue open for that to be implemented in the future.

**Comment by x1p** [comment]
Thnx.
There is a minor error in this default message:
```
SELL_PRICE_ABOVE_MAX: "Sell price is above maximum!"
SELL_PRICE_BELOW_MIN: "Buy price is below minimum!"
```
"Buy" must be "Sell".

**Comment by x1p** [comment]
It seems that the limits are bypassable when you change the number of items.
If you cant make a buy chest under 1 $ per item, you can make a buy chest with 5 items for 2 $ which is per item under the minimum limit.
This goes for all limits.

**Comment by x1p** [comment]
I'm afraid there is a miscalculation
```
min:
  buy_price:
    dirt: 2
  sell_price:
    dirt: 1
```
This should mean I can make a Buy shop:
```
sign:
1
B 2
Dirt
```
This works correct. When I make a shop 1 for 1, the message appears BUY_PRICE_BELOW_MIN
Now I can also make a sign like:
```
5
B 1
Dirt
```
This means 0.2 per item. No message appears. I can make the shop.
The same goes for Sell prices. 5 for S 1 is possible

The same goes for the maximum prices

**Comment by Phoenix616** [comment]
Yeah the logic was completely broken. 6d99210dd73aa91a26aaf173cb79e45371e61cf6 should really fix it now.

**Comment by x1p** [comment]
Thnx for all the trouble. It's seems to work just fine in tests
