### ISSUE TITLE
Change sign text color when chest is empty

### ISSUE THREAD

**Issue by ZonK256** [ChestShop-authors/ChestShop-3#195]
As title says, it would be convenient to have an option to change sign text color (i.e. to red) when shop is out of stock.

**Comment by Kryniowesegryderiusz** [comment]
I'd love to see it

**Comment by danisaacs** [comment]
Definitely a great idea if possible.  Currently having to use redstone contraptions to indicate to customers the chest is not empty.

**Comment by Kryniowesegryderiusz** [comment]
@Phoenix616 would it be added?

**Comment by Phoenix616** [comment]
> @Phoenix616 would it be added?

If someone PRs a proper solution for it, definitely. But this might also be possible just with a separate plugin module just by listening on the event similarly to how I did it in my ChestShopTools plugin.

What needs to be kept in mind though is that this only should apply to shops that actually sell items and needs to dynamically change when items are sold to the shop if the shop accepts both, selling and buying.

**Comment by JRoy** [comment]
I added this recently to my fork but needs a bit of work to fit the needs of this issue. Feel free to use it anybody who wants to add it to here: https://github.com/schlatt-co/ChestShopPlus/blob/master/ChestShop-3-Patches/0008-Add-sign-stock-indication-color.patch

**Comment by ZonK256** [comment]
Not exactly how proposed, but #368 solves this issue.
