### ISSUE TITLE
Chest Shops disappearing when server restarts

### ISSUE THREAD

**Issue by milothedalmador** [ChestShop-authors/ChestShop-3#199]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
Build 113
 
#### Plugin Config
https://pastebin.com/N3M5CFj3

#### Server Version
1.13.2
 
#### Server Log
Haven't got one (can restart and grab one if needed) 

#### What other plugins are you running?
Image attached.
![2019-02-05_01 06 51](https://user-images.githubusercontent.com/46726096/52247585-60026380-28e2-11e9-990a-633c474d7683.png)

#### What is happening?
Shops are fine setting up etc but when the server is restarted it won't load the database.

**Comment by Phoenix616** [comment]
You seem to have confused ShopChest with ChestShop which this repository is for. I suggest contacting the devs of the plugin you are using. (Or switching to ChestShop :wink:)
