### ISSUE TITLE
Disable shop is empty message

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [ChestShop-authors/ChestShop-3#200]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.9.3-SNAPSHOT (build 106) 
#### Plugin Config
Not  necessary
#### Server Version
Paper 1.13.2 
#### Server Log
Not  necessary
#### What other plugins are you running?
Not  necessary

#### What is happening?
/cstoggle not disabling shop is empty notifications
#### What did you expect to happen?
I would love to block shop is empty message to not get spammy

**Comment by Phoenix616** [comment]
Can you please provide your plugin config as requested in the issue template? Because there is an option called `CSTOGGLE_TOGGLES_OUT_OF_STOCK` in there which should do exactly what you want if set to true.

**Comment by Phoenix616** [comment]
Going to close this now, if the option did not fix the issue then please let me know with some more information on how you expect it to work/what doesn't work.
