### ISSUE TITLE
Item metadata IDs are not consistent

### ISSUE THREAD

**Issue by Phoenix616** [ChestShop-authors/ChestShop-3#202]
Item metadata now includes a so-called data version when serialized through Bukkit in order to provide backwards compatibility in case the serialzation changes. This results in different metadata IDs getting generated in ChestShop due to the internal metadata database comparing the serialized (and base 64 encoded) metadata to the ones existing in the database (and if it doesn't find one it inserts a new entry with a new ID)

~~A side effect of this ID generation seems to be that shops created with the old ID no longer accept the same item due to it generating a different metadata ID, this should be worked around by comparing the item that is sold directly to the one in the shop instead of the IDs.~~ This is not what's happening, there seems to be some other bug going on with that. Edit: They were actually two different items. One enchanted book had a repair cost while the other had not.

**Comment by danisaacs** [comment]
This is huge PITA.  Ebooks have different IDs depending on where they came from.  One if from Vill, another if from /repair, and yet another if from an Enchantment table.

**Comment by Phoenix616** [comment]
If the books have different NBT tags then they are different items and should be treated as such in ChestShop. Similarly to how Vanilla doesn't allow them to be stacked in the inventory either ;)

**Comment by danisaacs** [comment]
EBooks don't stack at all, same tag or not. :)

The 3 different tags are consistent, so it shouldn't be too much trouble to have CSN treat all three the same.

**Comment by Phoenix616** [comment]
Technically all items can stack, at least if they have the same NBT data and you remove the stacking limitations. But that's beside the point: If the items hale different properties then they will produce different codes. If you are sure that they behave exactly the same but still produce different output the please open a new issue (as this one is about the now fixed data version issue) and provide their NBT data (e.g. in a player.dat, as extracted text or in a vanilla give command syntax)

**Comment by danisaacs** [comment]
Will do!  Thanks, Phoenix616!
