### ISSUE TITLE
Add /shopinfo command

### ISSUE THREAD

**Issue by Phoenix616** [ChestShop-authors/ChestShop-3#203]
Add a command that provides some more information about a shop e.g. the prices, player information, stock amount (if enabled) or the item(s) being sold in the shop (as the metadata ID doesn't really tell a normal player anything).

Could be based on the [function](https://github.com/Minebench/ChestShopTools/blob/master/src/main/java/de/themoep/chestshoptools/ShopInfoCommand.java) in my [ChestShopTools](https://github.com/Minebench/ChestShopTools) plugin.

**Comment by Dom117** [comment]
I definitely think adding a way for players to see exactly what they're buying will elevate chest shops and players being able to sell custom items. Perhaps a player can look at the sign of a shop and run the /shopinfo command which will, in turn run the /iteminfo command..
