### ISSUE TITLE
ChestShop 1.8.8 item ID error

### ISSUE THREAD

**Issue by AlansS53** [ChestShop-authors/ChestShop-3#211]
#### Plugin Version
  3.9.2 (Build 86)

#### Config Plugin
  https://pastebin.com/bwRRW6rk

#### Server Version
1.8.8-R0.1-SNAPSHOT

#### Server Log
https://pastebin.com/rB71SLFX

#### What other plugins are you running?
SkinsRestorer, PermissionsEx, ViaVersion, AntiBotAttack, Vault, ProtocolLib, NoCheatPlus, Essentials, PlayerHeads.

#### What is happening?
* When players use / iteminfo command with trunks or boards of Dark Oak and Blaze heads display console error and command not work.
* When players place this items in the chest and put in the id of the object "?" the store is not created and shows the same error in the console, it does not work either, placing the minecraft id.

#### What did you expect to happen?
* That the command / iteminfo show the appropriate information.
* That the store can be created correctly with those items.

**Comment by Phoenix616** [comment]
The version you are using is not compatible with your outdated server version, either update your server or downgrade to a version of the plugin that was made for your server version.

**Comment by AlansS53** [comment]
Thanks you and sorry for taking away your time.
Build 68 works fine, https://ci.minebench.de/job/ChestShop-3/68/
