### ISSUE TITLE
Comparators can't detect items being sold

### ISSUE THREAD

**Issue by Sti-jn** [ChestShop-authors/ChestShop-3#217]
#### Plugin Version
2.10-SNAPSHOT (build 128)
 
#### Plugin Config
[config.zip](https://github.com/ChestShop-authors/ChestShop-3/files/3076424/config.zip)
 
#### Server Version
Paper version git-Paper-616 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

#### What other plugins are you running?
![image](https://user-images.githubusercontent.com/39404504/56082085-cf319200-5e14-11e9-8985-ba4435e1fa92.png)

#### What is happening?
When buying an item from a chest it no longer triggers comparators. This means contraptions like this (see image below), which are often used to sell "random" items, no longer work. It seems like the fix for issue #169 broke this.
![image](https://user-images.githubusercontent.com/39404504/56082208-33088a80-5e16-11e9-851f-c9f2e0ac54bd.png)

#### What did you expect to happen?
I expect to buy the only item in the chest which causes the comparator to send out a redstone signal allowing one new item to go into the chest and allowing one item to be dispensed from the dispenser.

**Comment by Phoenix616** [comment]
Uh, that's interesting. Probably have to send a manual block update to get that to work again.

**Comment by Sti-jn** [comment]
Correct, but that doesn't work if you want to keep it automated. Since you can't have players open the chest or update it in any other way since that means you have to allow them to build in that area which defeats the purpose

**Comment by Phoenix616** [comment]
Yeah I meant in the plugin directly, not a player manually. It's an interesting behaviour though, apparently "removing" the item from the chest by setting it's amount null does not result in the block getting updated in a way that would trigger a comparator where as before an inventory removal method was used which probably results in updates when used with a block's inventory.

Gonna have to think a bit about what would the right approach to fix this would be as just blindly sending a block update on the chest might result in other strange behaviour, but same thing could happen currently with setting the item's amount zero so I might just need to switch back some parts of the code to use the removal methods. I'll have to experiment a bit which one works best.
