### ISSUE TITLE
[1.14 UPDATE QUESTION]

### ISSUE THREAD

**Issue by tubatyler** [ChestShop-authors/ChestShop-3#224]
I know it's taboo to run developmental versions of Spigot/Bukkit, but I was wondering if ChestShops most recent build is compatible with Update 1.14?

**Comment by Phoenix616** [comment]
Seeing as Bukkit provides backwards support for older plugins it's
definitely compatible and will run, that's the whole point of the plugin
API.

Whether or not all features will work without any issues I don't know
though but 1.14 isn't nearly as big of an update as 1.13 was and some minor
issues that turned up when using 1.14 have already been fixed so I would
assume that it's at least as stable as 1.14 itself (which doesn't mean much
seeing as how broken the new version is I guess)

And as always: If you see any issue simply report them ;) I can't really
test all possible server setups myself.

**Comment by AzuzoraDev** [comment]
But it doesn't on 1.14.3 bukkit or paper...
