### ISSUE TITLE
Chest close animation isn't played after open from sign

### ISSUE THREAD

**Issue by JRoy** [ChestShop-authors/ChestShop-3#227]
#### Plugin Version
3.10-SNAPSHOT (build 137) 
#### Server Version
1.14
#### What other plugins are you running?
CoreProtect, LuckPerms, & Vault 

In 1.14, the chest close animation isn't played when closing a chest that was opened via the shop sign.

**Comment by Phoenix616** [comment]
Please provide your exact server version/make sure that you are running the latest version/a build after [the commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/09a453aede52dec3c3f307974396a9642de4c87c) that fixed a related bug in CraftBukkit.

**Comment by JRoy** [comment]
Just checked with the latest commit and it works, sorry for the confusion.
