### ISSUE TITLE
Build is Failing Due to Dependency Error

### ISSUE THREAD

**Issue by SurvivalQuest** [ChestShop-authors/ChestShop-3#233]
I cloned the repo today and attempted to build it, but I am receiving the build error below.

[ERROR] Failed to execute goal on project chestshop: Could not resolve dependencies for project com.acrobot.chestshop:chestshop:jar:3.10-SNAPSHOT: Failed to collect dependencies at de.themoep.showitem:api:jar:1.2.24: Failed to read artifact descriptor for de.themoep.showitem:api:jar:1.2.24: Could not transfer artifact de.themoep.showitem:api:pom:1.2.24 from/to minebench-repo (https://repo.minebench.de/): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed: NotAfter: Fri May 31 06:36:22 EDT 2019

I tried using the install_dependency_to_repo.sh script to add them from a previous ChestShop jar, but that resulted in the same error.

Could you please advise on what I could be doing incorrectly?
Also, it seems your SSL cert on ci.minebench.de expired and will not allow access.

**Comment by Phoenix616** [comment]
Apparently the nginx server didn't reload after renewing the cert the last time, sorry about that. Should be fixed now.
