### ISSUE TITLE
chestshop not work

### ISSUE THREAD

**Issue by Spark61** [ChestShop-authors/ChestShop-3#234]
Hello,
I have a 1.12.2 Paper Server. If I want to create a ChestShop, nothing happens. There is also no error in the console and the plugin is not disabled. I hope you can help me. If you speak German you can write me back in German.

**Comment by Phoenix616** [comment]
Please provide the information requested by the [issue template](https://github.com/ChestShop-authors/ChestShop-3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) otherwise there is no way to help you.
