### ISSUE TITLE
Error while generating full item name croshbow

### ISSUE THREAD

**Issue by andris155** [ChestShop-authors/ChestShop-3#240]
#### Plugin Version
[The full plugin version that you are running from /version ChestShop]
ChestShop version 3.10-SNAPSHOT (build 149)
 
#### Plugin Config
[The full config.yml file of ChestShop]
https://pastebin.com/cxTYcfVE
 
#### Server Version
[The full server version that you are running from /version]
This server is running Paper version git-Paper-94 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
 
#### Server Log
[The full latest.log file, especially important if you have a stack trace]

#### What other plugins are you running?
[List of your plugins, ideally with the version] 
Plugins (91): AdditionsAPI, AdminVedelem, antiRedstoneClock, AnvilRestrict, AreaShop, AsyncWorldEdit, BuntetesLogolo, ChatControl, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, CombatLogX, CommandHook, CommandSigns, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, EnderContainers, EntityDetection, EpicHeads, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HonapStaffja, HungerGames, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobArena, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoSpawnerChange, NoteBlockAPI, OpenInv*, Paintball, PickupSpawners, PinataParty*, PlaceholderAPI*, PlayerHeads, PlayerWarp, PlayerWarpTab, PlotSquared, PlugMan, PocketGames, PomaAdditions, RestrictedCreative, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, SzulinapiTuzijatek, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, Votifier, VotingPlugin, VoxelSniper*, WDLCompanion*, WDLCompanionGriefPreventionSupport*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

#### What is happening?
[Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!] 
Chestshop write error if use /iteminfo with crossbow
2019/06/18 17:23:33 Error while generating full item name
![59561183-79988200-901d-11e9-8714-df857d7bf6fb](https://user-images.githubusercontent.com/8324198/59697807-cbdccd00-91ee-11e9-8719-962c3087d10e.png)

#### What did you expect to happen?
[Explain what you expected to happen after performing the previously described steps]
Chestshop no write error

### Additional context
[Add any other context or screenshots about the feature request here.]

[And Delete the lines in square brackets!]

**Comment by Phoenix616** [comment]
Please provide the error from the log too.

**Comment by andris155** [comment]
No write error. Only write 2019/06/18 17:23:33 Error while generating full item name in chestshop log file.

**Comment by Phoenix616** [comment]
Please provide the full log file then.

**Comment by Bedah95** [comment]
same error on our Paper 1.14.3 -122 server 

[https://pastebin.com/DzLxLKMQ](https://pastebin.com/DzLxLKMQ

**Comment by Phoenix616** [comment]
> same error on our Paper 1.14.3 -122 server
> 
> https://pastebin.com/DzLxLKMQ

This is a different item and therefore issue. Please open a separate issue and provide the requested information as well as the give command or nbt of the item in question to test.
