### ISSUE TITLE
Integration of CustomModelData for the Keys

### ISSUE THREAD

**Issue by Lastphysics** [ChestShop-authors/ChestShop-3#245]
Hey, already want to say, you are making a very nice work with this plugin ;).

My idea is to implement the new item criteria : "CustomModelData" to the crate keys, so that we can give our own custom texture to the keys, wich would be so awesome.
What do you think of it ?

**Comment by Phoenix616** [comment]
This plugin does not provide crates nor keys for them? Did you by chance open this ticket on the wrong repo? :thinking:

**Comment by Lastphysics** [comment]
true, wrong plugin ^^, sorry for that?

But still nice work for your plugin
