### ISSUE TITLE
ChestShop Mods can't buy from ChestShops

### ISSUE THREAD

**Issue by SkuadMC** [ChestShop-authors/ChestShop-3#246]
#### Is your feature request related to a problem? Please describe.
The problem is that users with the "chestshop.mod" permission cannot buy from chest shops, as it just makes them open it instead.

#### Describe the solution you'd like
A toggle for "mod mode" would be the most helpful solution, but any way this could be implemented is appreciated.

#### Describe alternatives you've considered
I've considered creating a command that just adds and removes the permission for them, but I have yet to find a good way to do this using my current plugins.

**Comment by Phoenix616** [comment]
What's wrong with just disabling `IGNORE_ACCESS_PERMS` in the config?

**Comment by SkuadMC** [comment]
I mean there's probably nothing wrong with that, if it was there. Fresh config using the latest dev build from here https://ci.minebench.de/job/ChestShop-3/ (build 151 released on Jul 8).

That option isn't there. Closest thing is IGNORE_CREATIVE_MODE, which doesn't help me.

**Comment by Phoenix616** [comment]
It needs to be set to false in order for players with access permission to be able to use shop signs. What happens instead? Also can you please provide your full config as well as your log?
