### ISSUE TITLE
Out of stock spam

### ISSUE THREAD

**Issue by LogGits** [ChestShop-authors/ChestShop-3#256]
#### Plugin Version
3.10 snapshot build 151
 
#### Server Version
paper 1.13.2 build 639
 
#### Server Log
none

#### What other plugins are you running?
nothing relating to this issue

#### What is happening?
regardless of the state of /cstoggle players recieve spam of `"Shop is out of stock! (player tried to buy)"`

#### What did you expect to happen?
When /cstoggle is toggled off players shouldnt recieve spam of an out of stock shop.

### Additional context
use /cstoggle and make sure its off, have an empty shop and then get a player to spam rightclick. It will spam you with the shop out of stock message.

**Comment by Phoenix616** [comment]
Please provide your plugin config as requested in the issue template so that it can be checked for configuration issues related to your bug. (In your case especially the `CSTOGGLE_TOGGLES_OUT_OF_STOCK` option would be of interest)

**Comment by LogGits** [comment]
Oh sorry my bad i didnt see. Thanks a tonne 🙂
