### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by dinidusam** [ChestShop-authors/ChestShop-3#257]
#### Plugin Version
3.9,2
#### Plugin Config
It's all in this word document (I use Aternos as a hosting service so I can't put the file there
[Config file for Chestshop.docx](https://github.com/ChestShop-authors/ChestShop-3/files/3439543/Config.file.for.Chestshop.docx)
#### Server Version
1.14.4
 #### Server Log
[Log for MInecraft Server 324pm7282019.docx](https://github.com/ChestShop-authors/ChestShop-3/files/3439545/Log.for.MInecraft.Server.324pm7282019.docx)
#### What other plugins are you running?
ChairStairs 1.1
Essentials X 2.17.0.0
PermsEx 1.23.4
PlayerVaults 3.5.7
Vault 1.7.2

#### What is happening?
Chestshop doesn't work. I've put a chest down and slapped a sign on it like this for ex
(Username)
2
B2
Stone
Nothing ever happens, just like the plugin was never there, but it does start up and it does say it found the economy plugin I was using in the console. Yes I have tested if it worked with people. Yes I gave people the permissions.

#### What did you expect to happen?
I expected it to let people be able to buy stuff

### Additional context
![Screenshot (1111)](https://user-images.githubusercontent.com/48186568/62012662-c8722500-b14e-11e9-9058-4c384311fec3.png) 
-Permissions 
![2019-07-28_15 47 41](https://user-images.githubusercontent.com/48186568/62012682-138c3800-b14f-11e9-840b-8f67b0dbfa05.png)
-Chest isn't working

**Comment by Phoenix616** [comment]
For 1.13+ support please update to the test release or the latest development builds.
