### ISSUE TITLE
Buy/Sell all

### ISSUE THREAD

**Issue by LogGits** [ChestShop-authors/ChestShop-3#260]
#### Is your feature request related to a problem? Please describe.
I am using a plugin that is basically an extension of this plugin. Currently there is no way to sell/buy all items to/from a shop even using PreTransationEvent.

#### Describe the solution you'd like
The dev said that it would be useful if PreTransactionEvent had a `.setAmount(int amount, boolean adjustPrice)` that basically gets sets the amount of the item being sold and the boolean "adjustPrice" if true would basically update the price to fit the amount of new items.

**Comment by Phoenix616** [comment]
This should already be possible by editing the price and stock in the the [PreTransactionEvent](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Events/PreTransactionEvent.java) similarly to how the [PartialTransactionModule](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/PreTransaction/PartialTransactionModule.java) does it.

**Comment by LogGits** [comment]
Thanks a tonne :)
