### ISSUE TITLE
ChestShop.mod permission

### ISSUE THREAD

**Issue by AmazedMender16** [ChestShop-authors/ChestShop-3#266]
#### Plugin Version
3.10-SNAPSHOT ( BUILD 152 )
 
#### Plugin Config
Default config file
 
#### Server Version
Latest Paper 1.14.4

ChestShop.mod doesn't let users destroy other people their shops, it just opens it.

**Comment by Phoenix616** [comment]
Yes, that is [intentional](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/resources/plugin.yml#L87). Only admins can destroy shops. Fixed it in the Bukkit/Spigot description.

**Comment by AmazedMender16** [comment]
Thanks for the quick response, is there a sub permission to allow this? ( break shops but not allow admin shop creation? )

**Comment by Phoenix616** [comment]
You can grant `ChestShop.othername.destroy.*` to allow destroying of all player shops without any of the other admin permissions.
