### ISSUE TITLE
Chestshop LWC breaking.

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#267]
Recently got this bug report:

> 1. Place a chest, and make a shop.
> 2. Place a joining chest next to it
> 3. Lwc will be removed on both chests even if second is removed, and when you open the chest you no longer receive the lwc message. 
> 4. The chest is still inaccessible though so this isn't critical yet

I have confirmed this is indeed an issue.
If you make a single chest-chestshop and add a connecting chest, the LWC on the chest gets removed.

Our config:
https://pastebin.com/1Nr3LV58
Chestshop:
https://ci.minebench.de/job/ChestShop-3/152/
LWC:
https://ci.ecocitycraft.com/view/LWC/job/LWC-Dev/37/

Tagging @pop4959 incase it's something on LWC's end.
But I believe this is a fault with chestshops.

**Comment by pop4959** [comment]
If I'm understanding this correctly though, the other side of the chest still seems protected even though you don't receive a message. Perhaps you could try running some tool like LP verbose to see if the usual permission checks are being made by LWC on the chest when you attempt to open it.

Not sure what could be wrong, but feel free to keep me updated. I'll be around if you have any questions.

**Comment by andrewkm** [comment]
@pop4959 the actual LWC protection get's removed.
This is definitely a bug, highly leaning towards chest shop being the issue.

Easier demonstration:
1. Create the following:
https://i.imgur.com/F3eFuGn.png
Both sign and chest are protected automatically by chestshop.

2. Add a chest to the right:
https://i.imgur.com/f6shfmX.png
Chest lwc is completely removed. Sign remains protected. Chest remains un-openable as chest shop itself is still protecting the chest: https://i.imgur.com/p7c95Y4.png

**Comment by Phoenix616** [comment]
Could you please provide the missing information requested in the issue template especially your server version and your log? Because as far as I can tell from a quick test LWC protection is actually broken on 1.14.4.

**Comment by Phoenix616** [comment]
After making LWC protections work correctly (in f90d23cfc3d4c699c07b80f40dff59c331c48d18) I cannot reproduce the described behaviour (both chests seem to be properly protected) and I also kinda doubt that this is a ChestShop issue as I have heard several similar reports for my own LWC fork before without using the LWC protection in ChestShop (although I wasn't ever able to reproduce this issue...).

So we really need more information on how to reproduce this issue. (Or maybe my changes in the mentioned commit already fixed it somehow?)

**Comment by andrewkm** [comment]
This is fixed as of build 156: https://ci.minebench.de/job/ChestShop-3/156/
As such, closing ticket.
Appreciate the responses boys :)
