### ISSUE TITLE
Command to allow admins/mods to buy/sell from shop signs

### ISSUE THREAD

**Issue by JRoy** [ChestShop-authors/ChestShop-3#268]
#### Describe the solution you'd like
A command to toggle the `OTHER_NAME_ACCESS` permission to allow admins/mods to buy from chestshops without them just opening the chests

#### Describe alternatives you've considered
If I'm not mistaking you could make a change here https://github.com/ChestShop-authors/ChestShop-3/blob/a95f7316d6bb7d4ee84827313e990b3e83aa5487/src/main/java/com/Acrobot/ChestShop/Listeners/Player/PlayerInteract.java#L118-L132

**Comment by JRoy** [comment]
~$17 (In ETH) Bounty on this

https://www.bountysource.com/issues/79416477-command-to-allow-admins-mods-to-buy-sell-from-shop-signs

**Comment by g--o** [comment]
Hey working on this, just to be clear:
by admins: do you mean server admins (op perm) or shop admins (owners)

**Comment by g--o** [comment]
Can you please re-explain what the command should do?
Do you mean that shop owners can buy from themselves? Or do you mean Op users?
Also should the command have any parameters?

**Comment by JRoy** [comment]
@g--o I'd like users with the `ChestShop.othername.access` permission to do a command that toggles that permission so that users with that permission can purchase/sell to shops. The owner of a shop would still not be able to purchase from/sell to their own shop.

**Comment by JRoy** [comment]
@Phoenix616 please close this

**Comment by Phoenix616** [comment]
Implemented in 88a23a38dbd4f1bf22552300e9289e2a1aac89ee.

**Comment by Phoenix616** [comment]
@g--o please don't forget to claim your bounty [on bountysource](https://www.bountysource.com/issues/79416477-command-to-allow-admins-mods-to-buy-sell-from-shop-signs), seeing as they are going to keep any bounty that is older than two years after June 1st I would highly advice to at least claim it even though their ETH account linking is still not working properly :S

**Comment by g--o** [comment]
@Phoenix616 thanks a lot, i sorted a paypal transaction instead of the eth and opened an issue on bountysource's repo; that platform should really get itself together.. 

anyway you should probably email them to make sure everything's in order on your end as well;  thanks again :)

**Comment by Phoenix616** [comment]
Well I don't really have any control of the bounties there, it's all in the hands of bountysource unfortunately :S And seeing as you resolved it I think that you should just get that if in any way possible.

**Comment by g--o** [comment]
@Phoenix616 oh I see, i'll try. thanks again for the concern :)
