### ISSUE TITLE
Moderator/OP cant use shops

### ISSUE THREAD

**Issue by Disorbs** [ChestShop-authors/ChestShop-3#269]
#### Plugin Version
3.10 build 156
 
#### Plugin Config
https://paste.md-5.net/ezevutaqij.makefile
 
#### Server Version
1.14.4 build 175

#### What is happening?
Before we used the latest jar for 1.12.2 and in that jar we had perms for moderators of ChestShop.Mod ChestShop.Name.* ChestShop.Destroy.* to be able to create/destroy signs but with the new one now with those it allows Mods and OPs to not be able to use peoples sell signs as they just open the chest and removing those perms allows for them to use and create signs but now allow moderators to remove them since as soon as i add that it wont allow them to use the signs as it opens the chest]

#### What did you expect to happen?
For moderators to be able to create signs for players when they need help and also be able to use the sign shops as well as breaking them for people if needed

**Comment by Phoenix616** [comment]
Either remove permissions from them to access the shops (ChestShop.othername.access.*, see the [permissions page](https://dev.bukkit.org/projects/chestshop/pages/permission-nodes) for the other mod/admin permissions) or allow trading for people with access perms by disabling the `IGNORE_ACCESS_PERMS` config setting.

**Comment by Disorbs** [comment]
so that is the only option to just not let mods open shop chest from other people? why what did you change that needed to be made this way? still havent tried the second option dont really get what it means.

**Comment by Phoenix616** [comment]
If you want mods to be able to access shops but still trade then you need to use the config option to disable that they are ignored by the plugin. (similarly to creative mode)

That was changed when a bug was fixed which allowed trading with access which was not intended. The config option exists to restore the old, unintended and potentially abusable behaviour. (draining money by re-adding items to the shop)
