### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AggerTV** [ChestShop-authors/ChestShop-3#273]
How do I remove the 2 extra lines?
![image](https://user-images.githubusercontent.com/55299038/66138615-362f4700-e5ff-11e9-9bd0-705a8142dc59.png)

**Comment by Phoenix616** [comment]
I'm unsure what this has to do with ChestShop, please provide more details (ideally everything asked by the issue template)

**Comment by AggerTV** [comment]
Oups, I posted this on the wrong Github xD
My bad
