### ISSUE TITLE
Custom items in admin shops

### ISSUE THREAD

**Issue by eirikh1996** [ChestShop-authors/ChestShop-3#281]
Hello. Is there any way I can sell items with custom displayname/lore via admin shops?

**Comment by Phoenix616** [comment]
Yes, simply write the ID that /iteminfo provides on the sign or use the autofill functionality.

**Comment by eirikh1996** [comment]
And how do I use the autofill functionality? And to clarify, what I want to do is to make it so players can buy the custom items from the admin shop.

**Comment by Phoenix616** [comment]
By putting a question mark on the item line instead of the ID. Then it will ask you to click on the sign with the item you want to sell

**Comment by eirikh1996** [comment]
Nice. Thanks for the help
