### ISSUE TITLE
Can't create shops for items that include the letter i in their names (i think.).

### ISSUE THREAD

**Issue by zenginberkecan** [ChestShop-authors/ChestShop-3#290]
#### Plugin Version
ChestShop version 3.10 (build 165)
 
#### Plugin Config
[config.zip](https://github.com/ChestShop-authors/ChestShop-3/files/4123710/config.zip)

 
#### Server Version
CraftBukkit version git-Bukkit-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

#### Server Log
[latest - Copy.zip](https://github.com/ChestShop-authors/ChestShop-3/files/4123715/latest.-.Copy.zip)

#### What other plugins are you running?
ChestShop
EssentialsX-2.17.1.0
Jobs4.15.2
LandClaiming
PlotClaim1.1.0
PluginConstructorAPI
Vault

#### What is happening?
I cannot create shops for items with the letter i in their names such as Diamond and Firework Rocket. I write diamond but it turns to Dıamond, firework_rocket turns to Fırework Rocket I think that should be the problem.

#### What did you expect to happen?
I expected to successfully create a shop.

### Additional context
![Minecraft Screenshot 2020 01 28 - 20 32 15 11](https://user-images.githubusercontent.com/60400979/73289228-6d101500-420d-11ea-8380-58b775038855.png)

**Comment by JRoy** [comment]
Outdated plugin version and you're also using CraftBukkit. Use [Paper](https://papermc.io/downloads) with the latest plugin version and try again.

**Comment by zenginberkecan** [comment]
> Outdated plugin version and you're also using CraftBukkit. Use [Paper](https://papermc.io/downloads) with the latest plugin version and try again.

some veteran issues :') we all used to use bukkit, didn't noticed that it got old. thank you :)
