### ISSUE TITLE
Cannot create free shop with 0 price instead of "Free"

### ISSUE THREAD

**Issue by johncsuti** [ChestShop-authors/ChestShop-3#297]
#### Plugin Version
3.10.1 (Build 174)
 
#### Plugin Config
[config.zip](https://github.com/ChestShop-authors/ChestShop-3/files/4415572/config.zip)
 
#### Server Version
Paper version git-Paper-114 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
 
#### Server Log
Nothing in server log...

#### What other plugins are you running?
Plugins (55): AdvancedHelp, AuctionHouse, BentoBox, BuycraftX, ChatManager, ChatReaction, ChestShop, ConsoleSpamFix, CrateReloaded, DiscordSRV, dynmap*, EpicRename, Essentials, EssentialsSpawn, FastLeafDecay, Harbor, HeadDatabase*, HolographicDisplays, ID-Library, IllegalStack, Item2Chat, LiquidTanks*, Lottery, LuckPerms, Multiverse-Core, MyCommand, NBTAPI*, NoFlyZone*, PL-Hide, PlaceholderAPI, Playtimes*, PreventPortBypass*, ProtocolLib, Scoreboard-revision*, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SignSpy*, SilkSpawners, spark, StackCord, StackMob, StackMobBridge, SuperVanish, TAB, TimeVote, TitleAPI, UltimateAutoRestart, Vault, Votifier, VotingPlugin, Vouchers, WeatherVote, WorldBorderAPI*, WorldEdit, WorldGuard

#### What is happening?
Gives an error when I have permission. Place chest fill out sign like it shows on spigotmc throws the error in title.
![2020-04-01_09 51 46](https://user-images.githubusercontent.com/22971404/78146198-d5db5f80-73ff-11ea-8f12-a9d99788a448.png)
![2020-04-01_10 00 52](https://user-images.githubusercontent.com/22971404/78146203-d70c8c80-73ff-11ea-944d-5db21cb19ee0.png)
![2020-04-01_09 51 42](https://user-images.githubusercontent.com/22971404/78146207-d8d65000-73ff-11ea-903f-77c2c2c9c436.png)

#### What did you expect to happen?
Shop is created.

### Additional context
N/A

**Comment by Phoenix616** [comment]
First off: You are not using the latest build, if you would then it would tell you that the price is invalid.

Regarding your actual issue: 0 can not be used as the price, if you want a free shop use the term "Free" on the sign. I realise that this isn't ideal so I'm gonna classify that as an enhancement so that it can be added in the future.

**Comment by johncsuti** [comment]
Okay thanks. I wasn't sure what I was doing wrong. I also was unaware I was using a old version.
