### ISSUE TITLE
Problem with Shop

### ISSUE THREAD

**Issue by PassiHD2004** [ChestShop-authors/ChestShop-3#301]
I just wanted to create a shop with ChestShop Plugin. My server is a CityBuild Server, and players are getting an error message when trying to buy something. The error message is from Plotsquared, and says that the user is lacking permissions for use, and i've set flag use 323, but when i add a player to my plot as a helper, it's working... So please help me out of this situation...

**Comment by Phoenix616** [comment]
PlotSquared has a [wiki page for ChestShop compatibility](https://github.com/IntellectualSites/PlotSquared/wiki/ChestShop-Compatibility), please refer to that. If it's still not working then please contact the PS devs/support regarding that.
