### ISSUE TITLE
Putting dye on signs

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShop-3#306]
#### Plugin Version
 3.10.2-SNAPSHOT (build 180)

#### Plugin Config
just default

#### Server Version
 Purpur version git-Purpur-568 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

#### Server Log
-

#### What other plugins are you running?
WorldEdit Worldguard Wordlguard-extra flags

#### What is happening?
A player making buy-chests can't dye it's own sign
Normal signs placed on a block can be dyed using dye.
Normal chests with a sign works fine too.

#### What did you expect to happen?
I would expect the owner of a shop to be able to dye it's own sign

### Additional context
When using dark oak signs, coloring the text makes the text much more readable.
Staff can do this because /csaccess is default off however for an owner, right clicking opens the chest. Maybe I missed a setting. If so, then I'm all ears.
Background information about using dye in general: https://minecraft.gamepedia.com/Dye#Signs, in action: https://www.youtube.com/watch?v=Zr0kNE4gb9M

**Comment by Phoenix616** [comment]
You could disable the `ALLOW_SIGN_CHEST_OPEN` config option to allow that.

**Comment by x1p** [comment]
I didn't know that. Sounds logical.

**Comment by x1p** [comment]
Thnx, works
