### ISSUE TITLE
Shulker Boxes closing

### ISSUE THREAD

**Issue by trevor1097** [ChestShop-authors/ChestShop-3#312]
#### Plugin Version
3.10.2-SNAPSHOT (build 192)
 
#### Plugin Config
[config.txt](https://github.com/ChestShop-authors/ChestShop-3/files/4639169/config.txt)

#### Server Version
Paper 273 (MC 1.15.2)
 
#### Server Log
No errors

#### What other plugins are you running?
Luck Perms, Vault

#### What is happening?
With ChestShop installed if you are standing on a shulker box it will kick you out of the inventory,

#### What did you expect to happen?
keeps shulker inventory open

**Comment by Phoenix616** [comment]
ChestShop will not work without an economy plugin, please make sure to test with one installed.

**Comment by Phoenix616** [comment]
Reproduced it, apparently the server calls a PlayerTeleportEvent in that case which doesn't make a lot of sense Oo (ChestShop closes inventories automatically if that happens, I guess I can limit that to shop inventories for now)
