### ISSUE TITLE
Player name on shops changes to (playername):0

### ISSUE THREAD

**Issue by jugxd** [ChestShop-authors/ChestShop-3#322]
#### Plugin Version
![2020-06-12_08 13 08](https://user-images.githubusercontent.com/66807402/84452078-626b8f00-ac87-11ea-9027-51aab3b2a895.png)

#### Plugin Config
https://pastebin.com/znkxa9QT
 
#### Server Version
![2020-06-12_08 14 54](https://user-images.githubusercontent.com/66807402/84451621-34397f80-ac86-11ea-847e-fa03bed43ad0.png)

#### Server Log
[The full latest.log file, especially important if you have a stack trace]

#### What other plugins are you running?
![2020-06-12_08 18 10](https://user-images.githubusercontent.com/66807402/84451643-40254180-ac86-11ea-939b-d0539562498c.png)

#### What is happening?
If normal users (not opped players) create their shops, their name on the first lines turns into (playername):0

![2020-06-12_08 18 58](https://user-images.githubusercontent.com/66807402/84451375-7e6e3100-ac85-11ea-8074-b5108a8e39b1.png)

#### What did you expect to happen?
I was expecting this to happen.

![2020-06-12_08 18 27](https://user-images.githubusercontent.com/66807402/84451377-8037f480-ac85-11ea-91af-fe2bcdb7e7a6.png)

### Additional context
**Apparently,** I can open the one with (playername):0

![2020-06-12_08 30 40](https://user-images.githubusercontent.com/66807402/84451959-1587b880-ac87-11ea-92e7-be0f35df3b39.png)
But, can't on the original one.

![2020-06-12_08 30 47](https://user-images.githubusercontent.com/66807402/84451963-16b8e580-ac87-11ea-998f-691ff844cc23.png)

My server is on offline mode.

**Comment by Phoenix616** [comment]
This is expected behavior in order to be compatible with name changes. Basically if a player has used that name before with a different UUID then it will get appended by a unique identifier to properly identify both players. If you really want to drop the old player then edit the users.db SQLite database file directly and update the non-identifier name with the UUID of the new player.
