### ISSUE TITLE
1.15.2 Shops don't work!

### ISSUE THREAD

**Issue by karlovm** [ChestShop-authors/ChestShop-3#323]
#### Plugin Version
I tried to use several versions
![image](https://user-images.githubusercontent.com/51130679/84599198-f2245f80-ae78-11ea-856b-7a4775d2fd8f.png)

 
#### Plugin Config
Default
 
#### Server Version
1.15.2
![image](https://user-images.githubusercontent.com/51130679/84599208-0f592e00-ae79-11ea-933c-d6b656a30ab3.png)

 
#### Server Log
![image](https://user-images.githubusercontent.com/51130679/84599234-43ccea00-ae79-11ea-8ae7-81669b706d1b.png)
Only one message.

#### What other plugins are you running?
[List of your plugins, ideally with the version] 
![image](https://user-images.githubusercontent.com/51130679/84599244-51826f80-ae79-11ea-93ee-e42b6c1748da.png)

#### What is happening?
I create a shop but nobody can sell or buy

#### What did you expect to happen?
Buy and sell

**Comment by Phoenix616** [comment]
Please provide the full server log.

Also you should make sure that players can interact with the sign (it might get blocked by other plugins, your spawn protection or them being in adventure/creative mode) as well as that they don't have the permissions to access that shop (can be toggled by using `/csaccess` or the config setting)

**Comment by karlovm** [comment]
One second...

**Comment by karlovm** [comment]
I tested with Vaul and EssentialsX. Not working!

**Comment by karlovm** [comment]
Wait for lastest.log...

**Comment by karlovm** [comment]
![image](https://user-images.githubusercontent.com/51130679/84599769-34e83680-ae7d-11ea-93e5-146e8e51bea6.png)
https://pastebin.com/6Zi5SK9h

**Comment by Phoenix616** [comment]
Yeah, there aren't any errors there. Please make sure that none of the other things an issue (access permissions without toggled `/csaccess` bypass, spawn protection, other protection plugins).

Also although probably unrelated to your problem you might want to update to EssentialsX, Essentials hasn't been maintained in years now.

**Comment by karlovm** [comment]
I catch the problem. I was op. But now with TNE i have message: Economy account for this shop doesn't exists.

**Comment by Phoenix616** [comment]
That you are going to have to resolve with TNE, I don't really know how all economy plugins work.
