### ISSUE TITLE
Negating sell perm still allows creation of sell signs

### ISSUE THREAD

**Issue by JasonHorkles** [ChestShop-authors/ChestShop-3#325]
#### Plugin Version
3.10.1
 
#### Plugin Config
https://hasteb.in/uxocaror.yaml
 
#### Server Version
```
>.... [22:00:40 INFO]: This server is running Tuinity version git-Tuinity-"32ac48d" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [22:00:40 INFO]: Checking version, please wait...
>.... [22:00:40 INFO]: Previous version: git-Tuinity-"6f9ca4f" (MC: 1.15.2)
>.... [22:00:40 INFO]: You are 17 version(s) behind
```
 
#### Server Log
https://hasteb.in/natuyeko.md

#### What other plugins are you running?
`AdvancedWarn, AsyncWorldEdit, AsyncWorldEdit-BountifulAPI*, AuctionHouse, BountifulAPI, BungeeTabListPlus, BuycraftX, ChestShop, Citizens, ClearLag, CommandDoesNotExist, CommandHook, CommandSync*, CoreProtect, CraftBook, CrazyCrates, EditableSign, Essentials, EssentialsGeoIP, EssentialsSpawn, ExtraContexts*, GameModeInventories, GriefPrevention, GSit, Harbor, HolographicDisplays, InventoryRollback, Jobs, KeepDeathDrop, Lasso, LibsDisguises, LimitPillagers, LuckPerms, Matrix, mcMMO, Multiverse-Core, Multiverse-NetherPortals, PlayerParticles, PlayTimeTracker, PlotSquared, PremiumVanish, ProtocolLib, ShopGUIPlus, SkQuery, Skript, skUtilities*, Stress, TempFly, TimeIsMoney*, UltimateTimber, Vault, VeinMiner, Vivecraft-Spigot-Extensions, Votifier, VotingPlugin, Wild, WildStacker, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags`

#### What is happening?
People can create a sell sign even with the sell permissions set to false. `ChestShop.shop.create` appears to be the only permission it's listening to (even though it does check for the sell perms), which is required to create the buy signs as well.

#### What did you expect to happen?
I expected an error saying I don't have permission to create the sell sign.

### Additional context
LuckPerms verbose: https://luckperms.net/verbose/ENEVfLlenC

I also looked at the FAQ and messing with the perms it was talking about didn't seem to help either

**Comment by Phoenix616** [comment]
Two things: You are not running the latest development build, please test with that. Also what does your permission setup look like? Iirc you need to negate the create permission and then only grant the `ChestShop.shop.create.buy` one. (Both sell and buy are children of the general create permission)

**Comment by Phoenix616** [comment]
What error does a player get when they try it?

**Comment by JasonHorkles** [comment]
They don't have permission to do that

**Comment by JasonHorkles** [comment]
![image](https://user-images.githubusercontent.com/51760372/85162215-31a6cf00-b21e-11ea-9fee-456e277441a5.png)

**Comment by Phoenix616** [comment]
The auto fill issue should be fixed now, it only checked the create permission if there was no item on the sign before, it now checks the sell and buy permissions separately.

And if you managed to setup your permissions to do what you want then feel free to close the issue. For other errors not directly related to the permissions please then open a new one.
