### ISSUE TITLE
i did open a issue before few mins and i didnt get a proper solution. Just a redirect so if u just helped me out instead of redirtecting

### ISSUE THREAD

**Issue by Drainer2002** [ChestShop-authors/ChestShop-3#327]
> [13:32:55 WARN]: 116 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'items'
> [13:32:55 WARN]: 132 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL , UNIQUE (`code`))
> [13:32:55 WARN]: 139 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating table 'accounts'
> [13:32:55 WARN]: 140 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_uuid_idx' for table 'accounts
> [13:32:55 WARN]: 140 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_shortName_idx' for table 'accounts
> [13:32:55 WARN]: 140 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - creating index 'accounts_name_idx' for table 'accounts
> [13:32:55 WARN]: 149 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , `lastSeen` BIGINT DEFAULT 0 NOT NULL , PRIMARY KEY (`shortName`) , UNIQUE (`name`,`uuid`) )
> [13:32:55 WARN]: 153 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_uuid_idx` ON `accounts` ( `uuid` )
> [13:32:55 WARN]: 158 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
> [13:32:55 WARN]: 163 [Server thread] INFO com.Acrobot.ChestShop.ORMlite.table.TableUtils - executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_name_idx` ON `accounts` ( `name` )

**Comment by Drainer2002** [comment]
I deleted the user.db and same error occurs whenever I restart the server

**Comment by Phoenix616** [comment]
As said before: There is no error here, these are only info message by a used library that appear on some setups. Please provide your setup information in the original issue #49 instead of opening new, duplicate ones as of right now there is no known reason why it shows for some and not others (e.g. it doesn't show on any of my servers so I can't even test any possible solutions)
