### ISSUE TITLE
Setblock/Fill set to destroy won't show destroy particles

### ISSUE THREAD

**Issue by JasonHorkles** [ChestShop-authors/ChestShop-3#328]
#### Plugin Version
3.10.2-SNAPSHOT (build 205)
 
#### Plugin Config
https://hasteb.in/afaxaqem.yaml
 
#### Server Version
```
>.... [16:35:50 INFO]: This server is running Tuinity version git-Tuinity-"12efad6" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [16:35:50 INFO]: Checking version, please wait...
>.... [16:35:50 INFO]: Previous version: git-Tuinity-"32ac48d" (MC: 1.15.2)
>.... [16:35:50 INFO]: You are 3 version(s) behind
```
 
#### Server Log
https://hasteb.in/ifasihez.md

#### What other plugins are you running?
`Plugins (61): AdvancedWarn, AsyncWorldEdit, AsyncWorldEdit-BountifulAPI*, AuctionHouse, BountifulAPI, BungeeTabListPlus, BuycraftX, ChestShop, Citizens, ClearLag, CommandDoesNotExist, CommandHook, CommandSync*, CoreProtect, CraftBook, CrazyCrates, EditableSign, Essentials, EssentialsGeoIP, EssentialsSpawn, ExtraContexts*, GameModeInventories, GriefPrevention, GSit, Harbor, HolographicDisplays, InventoryRollback, Jobs, KeepDeathDrop, Lasso, LibsDisguises, LimitPillagers, LuckPerms, Matrix, mcMMO, Multiverse-Core, Multiverse-NetherPortals, PlayerParticles, PlayTimeTracker, PlotSquared, PremiumVanish, ProtocolLib, ShopGUIPlus, SkQuery, Skript, skUtilities*, Stress, TempFly, TimeIsMoney*, UltimateTimber, Vault, VeinMiner, Vivecraft-Spigot-Extensions, Votifier, VotingPlugin, Wild, WildStacker, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags`

#### What is happening?
When using fill and setblock commands set to destroy (e.g. `/setblock ~ ~1 ~ air destroy`) the block gets replaced and there is no destroy sound/particles

#### What did you expect to happen?
There should be sounds and particles like with vanilla

### Additional context
Tried it on the latest paper build as well and this issue doesn't happen when ChestShop is not installed.
[A video can be found here](https://1drv.ms/v/s!ArOS099NaR9Lh5kRaH-Hg3W3qrTlMw?e=GYqf6H)

**Comment by JasonHorkles** [comment]
Looks like the animation for breaking chorus fruit also has the same problem

**Comment by Phoenix616** [comment]
I don't think this has anything to do with ChestShop, it works like expected when I test it (with Paper 1.15.2 b380). It's either an issue with some other plugin or the client/network of yours. I suggest testing with no other plugin than what's necessary for ChestShop and the Vanilla client.

**Comment by JasonHorkles** [comment]
Can reproduce it on the latest 1.16.1 paper and dev build for ChestShop

Doesn't happen on spigot so must have something to do with "Using Paper's BlockDestroyEvent instead of the BlockPhysicsEvent!"

**Comment by Phoenix616** [comment]
Please provide some more information about your setup then (log, config, exact client, server and plugin versions as well as operating system of both the server and the client)

**Comment by JasonHorkles** [comment]
**Log**: https://hasteb.in/aculanej.md
**Config**: https://hasteb.in/wiyaciqi.yaml (default - newly generated folder)
**Client**: Vanilla 1.16.1 & OptiFine 1.16.1 Pre9
**Versions**: ![image](https://cdn.discordapp.com/attachments/335445132520194058/736627744103989268/unknown.png)
**Client OS**: Windows 10
**Server OS:** Windows 10 & Linux (happens on both my host and pc)
I made a freshly generated server and the issue still seems to happen with only Vault and ChestShop installed.
All I did was make a repeating command block doing `/setblock ~ ~1 ~ dirt destroy` and it shows the particles and plays the sound just fine without ChestShop, but doesn't do that with ChestShop

**Comment by Phoenix616** [comment]
Can you test without Optifine?

**Comment by JasonHorkles** [comment]
That's what I was saying when I wrote
> Vanilla 1.16.1

**Comment by Phoenix616** [comment]
Ok I can reproduce this on 1.16.1 (b114 still). Something must've changed from 1.15.2 to 1.16.1 which might have come from a patch which Tuinity already had in 1.15.2. It breaks as soon as the BlockDestroyEvent is used (even when not doing anythign special with it, this in itself is extremely odd).

**Comment by JasonHorkles** [comment]
Should I file a report to paper?

**Comment by JasonHorkles** [comment]
That works too haha
Thanks so much!!

I'll close the issue once it's merged into paper and can confirm it doesn't happen anymore

**Comment by JasonHorkles** [comment]
Appears to work properly now
