### ISSUE TITLE
Server stops responding ~20s if shop item count is 2147483647 

### ISSUE THREAD

**Issue by TheRBZ** [ChestShop-authors/ChestShop-3#329]
#### Plugin Version
3.10.1 (build 174)
 
#### Plugin Config
https://pastebin.com/m7B0Z6RC

#### Server Version
> version
[15:45:39 INFO]: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[15:45:39 INFO]: Checking version, please wait...
[15:45:39 INFO]: Previous version: git-Paper-371 (MC: 1.15.2)
[15:45:39 INFO]: You are 1 version(s) behind
 
#### Server Log
https://pastebin.com/f6K8NsU8

#### What other plugins are you running?
![image](https://user-images.githubusercontent.com/39860014/85950738-8fda5d00-b956-11ea-9be0-7955193a3c6c.png)

#### What is happening?
When a user creates a shop where you can buy 2147483647 items, it causes the server to stop responding for about 20 seconds. If they spam click it, the server crashes.

#### What did you expect to happen?
It should say "You can't create a shop for more than 64 items" or something, or it shouldn't lag at all like this.

### Additional context
![image](https://user-images.githubusercontent.com/39860014/85950782-c912cd00-b956-11ea-8500-353e455b63de.png)

**Comment by Phoenix616** [comment]
You are using an outdated version and not the latest development build, this is already fixed.

**Comment by TheRBZ** [comment]
thank you for replying so quick, will try this out

**Comment by TheRBZ** [comment]
Worked, thank you!
