### ISSUE TITLE
buying and selling not possible

### ISSUE THREAD

**Issue by Feier68** [ChestShop-authors/ChestShop-3#334]
#### Plugin Version
3.11 (build 213)
 
#### Plugin Config
https://hastebin.com/xiricoduho.makefile
 
#### Server Version
testet 1.16.1 paper
1.15.2 paper
 
#### Server Log
https://hastebin.com/yuyasuvuli.md

#### What other plugins are you running?
vault
reformcloud Perms
essentials

#### What is happening?
if someone (op or perms) tries to buy something in a shop 
 then "[shop] You dont have permission to sell" or "to do that"
even though he has rights or op

sry for the bad english (translator)

#### What did you expect to happen?
I have no idea because the players all have pems.

**Comment by Phoenix616** [comment]
By default users should have permission to crate and use shops so please test without granting any permission and without op.

If that works then OP or granting all permissions screwed something up an I would suggest to only grant the permissions you actually need.

**Comment by Feier68** [comment]
tested with and without it does not work and without op

**Comment by Phoenix616** [comment]
Please make sure that the user is able to interact with signs at the place of the shop (e.g. outside of the spawn protection as well as any other plugin's protection).

Beyond that you'll have to make sure that your permissions plugin actually uses the default permissions of plugins or that they are granted in a way that the [default permissions](https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/resources/plugin.yml#L35) are. You should also be able to check which permissions get checked with a permission plugin's verbose mode.

**Comment by Phoenix616** [comment]
No further reply or info provided, I assume this was solved.
