### ISSUE TITLE
Jpremium Hook

### ISSUE THREAD

**Issue by Cryptics1999** [ChestShop-authors/ChestShop-3#337]
The plugin cant be used whit our Jpremium authme plugin. The plugin creates a unique uuid for all players (premium and cracked)

The solution shoud be to make a hook into the Jpremium UUID so it reads that.
https://github.com/Jakubson/JPremiumCleared/wiki#developer-api
I think this is the hook that is needed from this page:
UUID getUniqueId()

Add a hook into the plugin so that it it reads the unique uuid of the player

#### Additional context
The issue is that cracked players cant make a shop but premium players can. It tells invalid username. Server is on offline mode

**Comment by Phoenix616** [comment]
The check can now by disabled with the new `ENSURE_CORRECT_PLAYERID` config option. Doing so can lead to issues for sales with offline shop owners so disabling that check is not supported and any issue should be tested by enabling the option first.
