### ISSUE TITLE
Cannot generate item info for shop sign for warped fungus on a stick

### ISSUE THREAD

**Issue by FoodCans** [ChestShop-authors/ChestShop-3#339]
#### Plugin Version
version 311 build 213
 
#### Plugin Config
https://pastebin.com/raw/7gYe4yfw
 
#### Server Version
1.16
 
#### Server Log
https://pastebin.com/raw/GMa8n3pY

#### What other plugins are you running?
Economy plugin

#### What is happening?
Cannot generate item info for warped fungus on a stick because the name is too long according to the exception logs

#### What did you expect to happen?
I expected to do /iteminfo and get a shop sign name for the item.

### Additional context
nop

**Comment by Crousus** [comment]
Same issue when you set a "?" in the last row and then rightclick it with the warped fungus on a stick.
