### ISSUE TITLE
Translate "B", "S" and "free" on signs

### ISSUE THREAD

**Issue by RoinujNosde** [ChestShop-authors/ChestShop-3#340]
#### Is your feature request related to a problem? Please describe.
It's not possible to translate "B", "S" or "free" on shop signs.

#### Describe the solution you'd like
An option in the config/local file to translate them.

#### Additional context
Sorry if this was requested before, couldn't find a similar issue.

**Comment by Phoenix616** [comment]
Basically what #237 requests, please provide additional ideas there.
