### ISSUE TITLE
Adminshop limitation, signboard layout editable

### ISSUE THREAD

**Issue by Prasodym** [ChestShop-authors/ChestShop-3#341]
I would also be happy about 2 new features :)
Function 1: Make adminshop sale limitable above the config. 

E.g.
# Default false switch on a limitation
ADMINSHOP_SELL: true
# Default 80000 Doller, indicates the limit in currency
 ADMINSHOP_SELL_LIMIT: 80000
# Default 24 H specify time in hours
ADMINSHOP_SELL_TIME: 24
#
This means that players can sell something in the adminshop but if they have already collected 80k from the adminshop you have to wait 24 hours to sell again.

# Function 2:

Make the sign layout editable also via config

**Comment by Phoenix616** [comment]
These ideas seem really close to #330 and #237 so please provide additional feedback there.
