### ISSUE TITLE
Could not pass event TransactionEvent to ChestShop v3.11.1-SNAPSHOT (build 224)

### ISSUE THREAD

**Issue by mercurialmusic** [ChestShop-authors/ChestShop-3#342]
#### Plugin Version
ChestShop v3.11.1-SNAPSHOT (build 224)
 
#### Plugin Config
https://gist.github.com/mercurialmusic/3505dd8174decabd5911fcb454d722f4
 
#### Server Version
Spigot git-Spigot-05da6fa-b0c6dfe (1.16.1)
 
#### Server Log
Error here: https://gist.github.com/mercurialmusic/39a84e031776d509aeff25ab2b92db2d

#### What other plugins are you running?
Potentially relevant: Residence 4.9.1.3 (most shops are within residence protection zones)

#### What is happening?
Most things seem fine in game, except for massive error spam in console every other time someone buys something, perhaps related to the messages sent to the shop owner if they're offline?

#### What did you expect to happen?
No spam.

**Comment by mercurialmusic** [comment]
Looks like disabling the transaction messages, both to the owner and the purchaser, seems to fix the spam for now.

**Comment by d00mfish** [comment]
I have the same problem with 3.11(Build213), but all the shops are located in worldguard regions and we dont have Residence so I would assume its not the fault of it.
Weirdly enough the errors just startet about 1 day ago.
The Selling and Buying works flawlessly but the errors just spam the console.

**Comment by Phoenix616** [comment]
@d00mfish Please provide your error too.

**Comment by d00mfish** [comment]
The Error when buying:
https://pastebin.com/24iL7g52
And when selling:
https://pastebin.com/DxNYPvBy

**Comment by Phoenix616** [comment]
@d00mfish you have a different error from what is reported here which is caused by you running an outdated build on a newer paper version than what existed when your ChestShop version was released. Update to the latest dev build and it should work.

**Comment by d00mfish** [comment]
Alright thank you, I thought I am on the safe side with the Bukkit releases but I will update asap ;)

**Comment by mercurialmusic** [comment]
I don't make my server logs or full plugin list public, but if there's something in particular that you're looking for I'll be happy to provide it. There really was nothing unusual in startup except a notification that my server account is set to "" (because I don't want to use that). 

This has been happening for me since the update to Spigot 1.16.1, which we did last week, and again, the errors went away when disabling the plugin's notification messages.

**Comment by Phoenix616** [comment]
This issue should be worked around now that the plugin uses adventure-text instead of bungeecord-chat for component messages. Please comment if you still get the same error on the latest builds.

**Comment by mercurialmusic** [comment]
So far so good! Thank you!
