### ISSUE TITLE
Massive DUPE BUG FOUND!

### ISSUE THREAD

**Issue by SladeHazard** [ChestShop-authors/ChestShop-3#355]
#### Plugin Version
3.9.2 (build 86)
 
 
#### Plugin Config
https://pastebin.com/fF7CSAB3

#### Server Version
1.12.2 Paper
 
/csgive Potion:8201 1 0720

The plugin doesn't check for spaces? and gets confused a player named 0720 is buying stuff and that command is being used to give him the stuff but it gives him the potion 10720 times?!

**Comment by SladeHazard** [comment]
uh can i get the fix for 1.12.2 version please?!

**Comment by Phoenix616** [comment]
It's fixed in the 1.12.2 builds.
