### ISSUE TITLE
Custom Alias config for NBT items

### ISSUE THREAD

**Issue by Corphix** [ChestShop-authors/ChestShop-3#360]
#### Is your feature request related to a problem? Please describe.
It can be a pain to figure out what book or sword or potion (items with custom nbt data) is being sold. While Potion#97 makes sense to the game, that could be anything to a player.

#### Describe the solution you'd like
Add a custom alias config for things like books, maps, potions, basically anything that uses nbt tags.

Potion#97 would become "Luck Potion":

```
custom_alias_1:
  item: 'Potion#97'
  alias: 'Luck Potion'
```

 Adding aliases to the config could be left to a permissions node, or simply editing and reloading the yml file manually. Loading a file with a conflicting alias (where 'Potion#97' is given the name 'Diamond', for example) would just default to the unmodified alias system to avoid conflicts/player scams.

#### Describe alternatives you've considered
I've looked at other plugins, but CS is too elegant to get rid of. 

#### Additional context
Would be willing to donate some $ to get this feature added.

**Comment by Phoenix616** [comment]
Once in a time this was supported by the plugin [OddItem](https://dev.bukkit.org/projects/odditem), unfortunately that project is rather dead. Theoretically this could be implemented by an addon plugin by simply listening on the MaterialParseEvent and ItemParseEvent so it wouldn't necessarily need to be in the core plugin.
