### ISSUE TITLE
Error while generating shop sign item name

### ISSUE THREAD

**Issue by baailey** [ChestShop-authors/ChestShop-3#363]
#### Plugin Version
3.10-SNAPSHOT (build 161)
 
#### Server Version
git-Paper-92 (MC: 1.16.1)
 
#### Server Log
I cannot show the full log as IPs would be visible, so here is the error instead - https://pastebin.com/Hziwt9rX

#### What is happening?
ChestShop generates an error when trying to sell a renamed Jack o' Lantern, or one with a lore. To reproduce, simply hold a Jack o' Lantern and do /rename test (I use EpicRename for this). Once it's renamed, create a ChestShop and add a ? on the bottom line, then try right-click to auto add the name and it should create an error for you. 

#### What did you expect to happen?
I know that the plugin shortens the name for a coloured shulker box, so I expected it to do the same since it seems the name becomes too long with the additional # info, which causes the error.

**Comment by Phoenix616** [comment]
Please test if this issue occurs on the latest development build. If it
still does then please provide the error log from Spigot or Paper and not
Tuinity...

**Comment by baailey** [comment]
using the latest dev build has fixed the issue.
