### ISSUE TITLE
No default config

### ISSUE THREAD

**Issue by seema84** [ChestShop-authors/ChestShop-3#371]
**Version:** ChestShop's version is: 3.11.1-SNAPSHOT (build 240)
 
**Server Version**
This server is running Paper version git-Paper-240 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
 
**Server Log**
[ChestShop] No default config 'local.yml' found in ChestShop's jar file!

#### What is happening?
after the update from 1.15.2 to 1.16.3 it received this warning

**Comment by Phoenix616** [comment]
First: You are not following the issue template. The most important part that is missing is the full server log.

Second: Unless there are any other issues then this is not an issue. There basically is no default config for the old local.yml in the jar file as that is no longer provided by the plugin but it tries to still use your old local.yml if it was found in the plugin's folder. If you want that warning to be gone convert your setup to the new language files as stated in the [update notes](https://github.com/ChestShop-authors/ChestShop-3/releases/tag/3.11).

**Comment by seema84** [comment]
okay thank you
