### ISSUE TITLE
/iteminfo is not working

### ISSUE THREAD

**Issue by ArnoPompio** [ChestShop-authors/ChestShop-3#389]
#### Plugin Version
Chest Shop Build #260
 
#### Server Version
paper-1.16.4-345.jar

#### What is happening?
/iteminfo is not working on last dev build. It's looking like this https://imgur.com/vLHwVnQ

#### What did you expect to happen?
Anything but not what I have on the picture.

I am sorry about the lack of information, but I don't have any ideas of what the command was doing normally. It's a player that pointed me of the problem.

**Comment by Phoenix616** [comment]
You are still using the legacy local.yml file, either remove that and use the new language files or add the missing language keys into that file as stated in the message. You also have a warning about this in your terminal/server log.
