### ISSUE TITLE
Players can open all shops

### ISSUE THREAD

**Issue by s7an1slaw** [ChestShop-authors/ChestShop-3#390]
Hello, after I put the plugin and some players made a chest shop and told me that they can open the shops of other players, the sign they put allows them to do so. They can't buy and when they click it, they open a chest and can take items from it

**Comment by Phoenix616** [comment]
That sounds like you have granted them with mod/admin permissions. (By default only ops have those permissions) Please make sure that you have setup your permissions correctly.

If you are sure then please provide the information requested by the [issue template](https://github.com/ChestShop-authors/ChestShop-3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) as well as as an output of your permission plugin's verbose mode on shop interaction and overall permission setup (e.g. with LuckPerm's tree function)

**Comment by s7an1slaw** [comment]
yes I gave them a chestshop.* rights by mistake :D
