### ISSUE TITLE
Material#FF issues

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShop-3#391]
#### Is your feature request related to a problem? Please describe.

Chestshop places #xx behind the material. These 2 characters make abbreviations and even words with the characters before that.
This causes the chat filter to falsely replace/deny the sign.
These 2 characters are mysterious to many players and nobody understands these codes.

#### Describe the solution you'd like

An option to hide these #characters

#### Describe alternatives you've considered

The only workaround currently is to include all possible exceptions in the chat filter.

#### Additional context

Example
![Sreenshot](https://user-images.githubusercontent.com/28690790/103425797-1cd7ca80-4bb5-11eb-82c6-737b0729d5dd.png)

Maybe somewhat related to issue no 360

**Comment by Phoenix616** [comment]
This is not really possible, the ID at the end of the name specifies which meta data an item has (it's a Base62 encoding of the ID in the items.db database). Hiding that somehow would make it impossible for players to a) know which item the shop sells via `/iteminfo` and b) create shops buying that exact item. It would also go against one of the goals of the plugin of providing all necessary information to setup a shop on the sign itself.

As for your filtering problem: I suggest using a regex to allow those codes in the item line.

**Comment by x1p** [comment]
>  I suggest using a regex to allow those codes in the item line.

That's indeed my only workaround. But this is the hard way. I just think it would have been better to solve the cause rather than the symptoms.
Thnx though.

**Comment by Phoenix616** [comment]
That's not really hard, a regex like `^[\w ]+#\w+$` should match all item strings with custom IDs

**Comment by x1p** [comment]
Actually, it's just not to match. But the regex is not the issue.
