### ISSUE TITLE
Unable to right-click

### ISSUE THREAD

**Issue by lucasantunespires** [ChestShop-authors/ChestShop-3#409]
I'm not able to right-click. Even when the buy/sell clicks are inverted, I just can't right-click. How do I fix that?

**Comment by Phoenix616** [comment]
There is a ton of missing information here. Please provide all of the one requested in the [issue template](https://github.com/ChestShop-authors/ChestShop-3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)...

**Comment by dd880602** [comment]
I am building a SHOP in the reserve
Right-click cannot be used to use SHOP in the protected area
Hope to be able to add the option to modify the button
EX: keyboard S to sell, keyboard B to buy

**Comment by Phoenix616** [comment]
> I am building a SHOP in the reserve
> Right-click cannot be used to use SHOP in the protected area
> Hope to be able to add the option to modify the button
> EX: keyboard S to sell, keyboard B to buy

It is not possible to catch arbitrary keyboard keys from the server, the client doesn't send those. You are going to have to check how to enable shop sign interactions in your protection plugin.

**Comment by Phoenix616** [comment]
No reply, I assume this was solved.
