### ISSUE TITLE
comparator send not signal but doublechest is empty *update

### ISSUE THREAD

**Issue by Rennbahn2000** [ChestShop-authors/ChestShop-3#412]
#### Plugin Version
3.11.1-SNAPSHOT (build 248)
  </details>
 
#### Server Version
papermc 1.16.4 version 416
//SECRETCRAFT (SERVER) 

#### What is happening?

**Single Chest:**
Comparator updated after buy. Works perfekt.

**Doublechest Chest:**
Comparator updated not after buy. Works not.
Comparator continues to send a signal when the Chest is empty.

@Issies 217 similar problem

![chest](https://user-images.githubusercontent.com/38062236/108950202-20904680-7666-11eb-9b6a-af0341fd75f2.jpg)

**Comment by Schwabba** [comment]
Got the same problem. When you empty a chest, the comparator only updates on single chests. If you use a double chest, you can empty the chest without the redstone signal getting updated.
