### ISSUE TITLE
Shift to sell 64x

### ISSUE THREAD

**Issue by AggerTV** [ChestShop-authors/ChestShop-3#417]
#### Is your feature request related to a problem? Please describe.

First of, I'm sorry if this is already an feature, and if it is already and feature, then there is something broken in my end.

Say I have a sign shop that sells 1 stone, and I want to sell all the stone I have in my hand, I shift click on the sign to sell my entire hand so I don't have to click the sign whatever many times.

#### Additional context

Server version: Tuinity version git-Tuinity-"5b6d8be" (MC: 1.16.5)
Plugin version: ChestShop version 3.11 (build 213)

**Comment by Phoenix616** [comment]
That is already a config option: `SHIFT_SELLS_IN_STACKS`. If you have that enabled and it still doesn't work then please provide the information requested in the [bug report template](https://github.com/ChestShop-authors/ChestShop-3/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
