### ISSUE TITLE
Premium accounts can't create shop

### ISSUE THREAD

**Issue by NexttiEmpixel** [ChestShop-authors/ChestShop-3#419]
Plugin Version
- Latest version in Spigot page

I have one plugin called nLogin who let premium accounts login with no verification (whitout /register).
The problem is: Only pirate accounts can create shop sign. The original players shows "Player not found" qhen they try to create shop sign.

I read this issue and i think that is the problem: https://github.com/ChestShop-authors/ChestShop-3/issues/337
But i cant found the ENSURE_CORRECT_PLAYERID resource in configs.

Sorry about my bad english! Tell me if u cant understand anything pls

**Comment by Phoenix616** [comment]
If it's not in the config then you are running an outdated version, update to at least the build which started to include that change.
