### ISSUE TITLE
Add Admin Shop name bypass

### ISSUE THREAD

**Issue by Krakenied** [ChestShop-authors/ChestShop-3#420]
Related to https://github.com/ChestShop-authors/ChestShop-3/commit/f68a3203acb86bfe95298c44e3c381b9aea03935

Players can't use admin shop named "Admin Shop"

**Comment by MrKrakenied** [comment]
https://github.com/ChestShop-authors/ChestShop-3/blob/a3c5ec618a5cfc2b7c760e149753f5faa07ca3f6/src/main/java/com/Acrobot/ChestShop/Listeners/PreTransaction/InvalidNameIgnorer.java#L22

It should be `(!ChestShopSign.isAdminShop(name) && !USERNAME_PATTERN.matcher(name).matches())`

**Comment by Phoenix616** [comment]
As far as I can tell admin shops work just fine? Please provide information on what bug you are experiencing/how to reproduce it.

Also that check was not really modified in the mentioned commit (only thing changed was that the player name pattern is now configurable) and it prevents players that try to abuse the plugin by using the same username as the admin shop is set to. If that was changed to what you suggest that prevention would no longer work.

**Comment by Phoenix616** [comment]
Closing as there was no further response and admin shops cork fine in testing.
