### ISSUE TITLE
Variable problem in the French translation

### ISSUE THREAD

**Issue by thedourn** [ChestShop-authors/ChestShop-3#429]
Hello
There is a problem on some lines (44 and 48) with the %amount variable.
![image](https://user-images.githubusercontent.com/42806467/112887498-817ec480-90d3-11eb-81cb-b81946cc2b89.png)

Thank
Thedourn

**Comment by Phoenix616** [comment]
Translation issues should ideally be dealt with via [Crowdin](https://crowdin.com/project/chestshop-3) as that will also always have the latest translation state.

**Comment by Phoenix616** [comment]
Closing as this should be done in Crowdin, not sure why I didn't originally close it directly.
