### ISSUE TITLE
color formatting

### ISSUE THREAD

**Issue by seema84** [ChestShop-authors/ChestShop-3#437]
#### Plugin Version
3.12-SNAPSHOT (build 290)
 
 
#### Server Version

 This server is running Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 

#### What is happening?

color formatting does not work completely

example (german lang file lang.de.yml):
NOT_ENOUGH_SPACE_IN_YOUR_SHOP: "[&7Dein &f%item&7 Shop ist &fvoll&7! &8(Mehr Infos)](&7Verkäufer: &f%seller\n&7Price: &f%price\n&7In Welt: &f%world\n&7Position: &f%x/%y/%z)"

**this will show the complete line in &8 (dark gray)**

#### What did you expect to happen?

functioning formatting

**Comment by Phoenix616** [comment]
Should be fixed now with https://github.com/Phoenix616/MineDown/commit/d36cfc8c9536ceb4fd2d4becfab1bfa96cb0fa46 (included starting with build 299)
