### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Malay1121** [ChestShop-authors/ChestShop-3#447]
I am facing issue, whenever I buy something, I get the item, money goes and other person gets but nothing comes in the chat, I also did everything true in config.yml for the message to show but it doesn't show :(

**Comment by Phoenix616** [comment]
Please provide the info requested by the issue template like your config and full log.

**Comment by Phoenix616** [comment]
No information provided in almost a month, closing this. If this is still an issue then please open a new one with all the requested information.
