### ISSUE TITLE
Diable a message

### ISSUE THREAD

**Issue by Boro221** [ChestShop-authors/ChestShop-3#448]
Hey!

I just have a question. Is it possible to disable this message:

NOT_ENOUGH_STOCK_IN_YOUR_SHOP: "[%price %item&7 shop is out of stock!](&f%buyer&7 tried to buy\n&7In world: &f%world\n&7At position: &f%x/%y/%z)"

**Comment by Phoenix616** [comment]
Depends on what you mean by "disable", if you mean the possibility to disable every message globally then setting it to empty should work (if it doesn't then that might be a valid enhancement), if you just want to disable that message for all players then you can also use the `SHOW_MESSAGE_OUT_OF_STOCK` config option, and if a player just wants to disable it temporarily then they can use the `/cstoggle` command to disable all shop notifications.

**Comment by Boro221** [comment]
oh thanks nevermind. I did not notice this option in config
