### ISSUE TITLE
Error occurred while enabling ChestShop v3.12.1-SNAPSHOT (build 322)

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#474]
### What is happening?

Paper 1.16.5 Build 788
ChestShop 3.12.1 Build 322 is broken.
ChestShop 3.12.1 Build 321 is fine.

### What did you expect to happen?

It to work.

### Plugin Version

3.12.2 322

### Plugin Config

Default generation, same issue.

### Server Version

1.16.5 788

### Server Log

Private request.

### What other plugins are you running?

Private request.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest build available from https://ci.minebench.de/job/ChestShop-3/.
- [X] I am running a version that has support for the type of issue.

**Comment by andrewkm** [comment]
Wait no, the problem isn't Java 16, it's this:
https://github.com/ChestShop-authors/ChestShop-3/commit/986a22fb73c86a72539880afbf30ecc5124c60c6

**Comment by Phoenix616** [comment]
That commit didn't touch anything related to the error. The error seems to be some issue in the adventure text platform library. That new build might've pulled in a broken version or something, gonna have to take a closer look at that.

**Comment by andrewkm** [comment]
Yeah, I noticed that prior to my edit. It's Jenkins related or something if the sort.
