### ISSUE TITLE
Crash server on enabling ChestShop (1.12 pre5)

### ISSUE THREAD

**Issue by andris155** [ChestShop-authors/ChestShop-3#48]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/26284939/3df65a68-3e46-11e7-8261-874d42fab3cf.PNG)

**Comment by TheChampTF** [comment]
Can confirm this

**Comment by mibby** [comment]
Am able to confirm as well. Hopefully 1.12 support won't take long!

**Comment by BillyGalbreath** [comment]
There's a 1.12 branch and available dev build. I won't have time to test it until this weekend, but one of you guys might be able to sooner.

More info in the comments on the dbo project page https://dev.bukkit.org/projects/chestshop

**Comment by TheChampTF** [comment]
At least stopped crashing things now. Thanks!

**Comment by haugsvar** [comment]
I can confirm the server doesn't hang on loading the plugin.

**Comment by Phoenix616** [comment]
Plugin works now with 1.12.
