### ISSUE TITLE
Cannot use the plugins !!! 

### ISSUE THREAD

**Issue by Appolon24800** [ChestShop-authors/ChestShop-3#488]
### What is happening?

when I put the panel it goes with [Lockette] (yes I have the lockette plugins) and if I delete the [Lockette] it goes back so thank you if you can solve its problem (I am in 1.12.2 and the version of the plugins is in 3.9.0 (Build # 52) thank you 

### What did you expect to happen?

when I put the panel it goes with [Lockette] (yes I have the lockette plugins) and if I delete the [Lockette] it goes back so thank you if you can solve its problem (I am in 1.12.2 and the version of the plugins is in 3.9.0 (Build # 52) thank you 

### Plugin Version

 3.9.0 (Build # 52)

### Plugin Config

<details><summary>Config</summary> ''yaml [Mettez la configuration ici] ''' </details>@media

### Server Version

1.12.2

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

Plugins (62): ArmoredElytra, AutoMiner, BackpacksRemastered, BanGUI, BankNotes, BetonQuest, ChatFormat, ChestShop, ClearChat, ClearLag, CreativeGates, CustomChatPrefix, Elevator, Essentials, EZWelcome, Factions, GUIShop, HealthBar, HolographicDisplays, Invsee, KInvBackup, LandClaiming, Lockdown, Lockette, LuckPerms, LuckyBlock, MassiveBooks, MassiveCore, MassiveHat, MassiveTickets, Multiverse-Core, Multiverse-Inventories, MyCommand, MyPet, MySQL, NametagEdit, PicoJobs, PlaceholderAPI, PlayerParticles, PluginConstructorAPI, PowerMining, RandomBox, ScoreBoard, SilkSpawners, SimpleBottler, SimpleFlyPlugin, SimpleSpawn-Core, SimpleTpa, sTablist, SuperVanish, Timber, TradeSystem, TuxTwoLib, UltimateChairs, Vampire, Vault, ViaVersion, Warps, WG-GUI, WhitelistPlus, WorldEdit, WorldGuard

### Agreements

- [X] I have checked if there are already similar issues open.
- [ ] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [ ] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
Well you haven't provided your config but try disabling (or enabling) Lockette support. Beyond that use a supproted version.
