### ISSUE TITLE
Money is a specific item

### ISSUE THREAD

**Issue by AbsDataStruct** [ChestShop-authors/ChestShop-3#492]
### Is your feature request related to a problem? Please describe.

"Money is an item" is an enhancement feature that would enable the use of a specific item (such emerald) as money rather than the money balance of economy system.

Minecraft is a blocks and items game, I like the way we can see all what we have in Chest or Inventory. Money balance is not as visual as a stock of wood in a chest. Children and rich players would love to see how much money they really have in stack of money in stacks of chests.
When the "money is an item" enhancement is activated, a specified item such emerald would become the coin used to sell and buy items for all shops, storing stack of money in Inventory or Chest.

### Describe the solution you'd like

The way to buy and sell with a ChestShop would be then only a simple exchange of money item such emerald with the purchased item. The Shop's Chest itself would continue to contain only the item to sell or buy, but allowing the owner to put many other chests under the top shop chest itself to store the owner's money used for transaction.

When a player BUY items, he would received items from the ShopChest as usual but the amount of money to pay would be taken from his Inventory as stack of the money item and put in one of multiple chests placed under the ShopChest.
When a player SELL items, he would put his items into the ShopChest as usual but the amount of money to earn would be taken from the multiple chests placed under the ShopChest and put into his Inventory as stack of the money item.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

### Additional context

![2021-11-29_21 06 51](https://user-images.githubusercontent.com/78984720/143935439-bf76fbb5-96b5-4911-8954-1fc5a564aeb6.png)

**Comment by AbsDataStruct** [comment]
A ChestShop's content
![2021-11-29_21 14 16](https://user-images.githubusercontent.com/78984720/143936289-9622b661-2b0a-4ffa-94cb-72b03c6037b8.png)

A Money item Chest's content
![2021-11-29_21 12 08](https://user-images.githubusercontent.com/78984720/143936039-367c6805-aec4-4ca8-94a7-9060d0cb0010.png)

**Comment by AbsDataStruct** [comment]
Sorry That system could be made by using the Gringotts plugin !
I searched for that !!!
Thanks Phoenix616

**Comment by AbsDataStruct** [comment]
To go further, I will ask anyway an enhancement to the ChestShop plugin that would force player to pay with a specific money item from their inventory rather than using the vault plugin. Only the shop owner would receive/give money item using the vault (Gringotts).
The goal is to force player to carry their money items in order to buy/sell items ! No electronic payment allowed !
The actual economy plugins does not make difference between account money and carried money ... so it would helps if the ChestShop could force payment of player from and to his inventory rather than through the traditional vault payment system...

**Comment by Phoenix616** [comment]
Well as I already stated at least part of it can be done with an item based economy like Gringotts.

The other part of using a Chest next to the shop or the shop chest itself could probably be done with a custom economy event listener but I don't think that's something to e included in the base plugin (as it is mainly focused on virtual Vault economies) but should be done with an addon if anyone needs that. Of course if there are specific changes in ChestShop in order to get such an addon working e.g. include more info in the events itself then I'm obviously open for that but I personally wont be writing such an addon any time soon.

**Comment by AbsDataStruct** [comment]
You're right, I will configure my server and check out what need to be done.
Thank you so much for your help.
