### ISSUE TITLE
In-game log command

### ISSUE THREAD

**Issue by baailey** [ChestShop-authors/ChestShop-3#500]
### Is your feature request related to a problem? Please describe.

Players are unable to track who purchased what from their store unless they are online. 

### Describe the solution you'd like

I would like players to gain access to a `/cs log` command that lists all purchases made via their shops, including when others sell to them as well. I have had numerous players talk about a feature like this, so thought I'd suggest it. A command that shows all buy/sell logs would be convenient too, as only OP's have access to the chestshop log files on my server and I'd like to give Admins access to the command. Could be `/cs log all` or something, not sure.

### Describe alternatives you've considered

None.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment]
Please see [ChestShopNotifier](https://github.com/ChestShop-authors/ChestShopNotifier/) for an addon plugin with that exact functionality.
