### ISSUE TITLE
not working plugin

### ISSUE THREAD

**Issue by PorcooDio** [ChestShop-authors/ChestShop-3#511]
### What is happening?

i have installed the plugin

### What did you expect to happen?

when i do /pl the plugin shows up red and it doesnt work.

### Plugin Version

3.12 build 307

### Plugin Config

[config.txt](https://github.com/ChestShop-authors/ChestShop-3/files/8421533/config.txt)

### Server Version

1.18.1 spigot implementing api version 1.18.1-RO.1-snapshot

### Server Log

[console.log](https://github.com/ChestShop-authors/ChestShop-3/files/8421557/console.log)

### What other plugins are you running?

![2022-04-05_22 14 34](https://user-images.githubusercontent.com/103072554/161841426-747572ac-b969-4a07-b224-53c1bbbeeb9e.png)

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
> [21:57:39] [Server thread/ERROR]: [ChestShop] No Economy adapter found! You need to install either Vault or Reserve!

You need to install an economy adapter. (Most likely Vault)
