### ISSUE TITLE
Add support for bedrock players in crossplay servers

### ISSUE THREAD

**Issue by GalaxyStylix** [ChestShop-authors/ChestShop-3#512]
### Is your feature request related to a problem? Please describe.

I run a crossplay server that runs on Paper and Geyser, when bedrock players try to purchase something from my admin shop it says "invalid username" (I tried on my bedrock account as well) since Bedrock users have a . in front of their names to differentiate them from Java users, my name for example would be GalaxyStylix on Java and .GalaxyStylix when I join my server from Windows 10 Edition.

### Describe the solution you'd like

Update the username recognition feature so crossplay servers can also use the plugin with no issues.

### Describe alternatives you've considered

I've used the plugin in different Java roleplay servers so I'm used to it myself and I don't think there's any good crossplay alternative that's as user friendly and simple as this one.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment]
Already possible by adjusting the config (`VALID_PLAYERNAME_REGEXP` and `ENSURE_CORRECT_PLAYERID)

See the comments in the config about the details.
