### ISSUE TITLE
Not working with floodgate/geyser

### ISSUE THREAD

**Issue by mrcoffee1026** [ChestShop-authors/ChestShop-3#517]
### What is happening?

States "invalid username" when bedrock player (username preceeded with a "+") tries to purchase anything.

### What did you expect to happen?

Should be able to purchase items as usual.

### Plugin Version

3.12.1-SNAPSHOT (build 345)

### Plugin Config

# This makes sure that the UUIDs of player shop accounts match the server's online-mode setting. Disabling this might lead to issues with offline players and is therefore unsupported!
ENSURE_CORRECT_PLAYERID: false
# This regexp validates the name of the player. If the name doesn't match, the player will neither be able to create a valid shop sign, nor buy/sell from a shop.
# Note for Bedrock support: If you have Floodgate on your server, you should set this regexp to ^\\*?\\w+$ and ENSURE_CORRECT_PLAYERID to false
# If your Floodgate prefix is not *, change the first * in the regexp (the one before the question mark) to whatever your prefix is.
VALID_PLAYERNAME_REGEXP: "^\\*?\\w+$"

### Server Version

This server is running Paper version git-Paper-357 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f210f67)

### Server Log

n/a

### What other plugins are you running?

n/a

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
Well you have not set your VALID_PLAYERNAME_REGEXP properly to accommodate for your prefix.

**Comment by mrcoffee1026** [comment]
I copied the regex from the documentation exactly, if that's not correct then what should the documentation be saying instead?

**Comment by mrcoffee1026** [comment]
Yes, you're right, failed to read the "replace the *" part, sorry.  Thanks for the help!
