### ISSUE TITLE
NPE trying to sell items

### ISSUE THREAD

**Issue by NoChanceSD** [ChestShop-authors/ChestShop-3#52]
This error just spams in console 
https://pastebin.com/KAr7pL06

Might be from iconomy (which i should totally stop using but didn't yet) but i don't think so. 
Started happening after updating to 1.12.

**Comment by Phoenix616** [comment]
This seems to be an issue with iConomy6 and not with ChestShop.
```
Caused by: java.lang.NullPointerException
    at com.iCo6.system.Queried.hasAccount(Queried.java:311) ~[?:?]
    at com.iCo6.system.Accounts.exists(Accounts.java:10) ~[?:?]
```

**Comment by NoChanceSD** [comment]
No, it wasn't with ico. I solved it anyway.

**Comment by Phoenix616** [comment]
So what was the issue then?
