### ISSUE TITLE
Shop not created, blank sign despite players given perms to make shops in LuckPerms

### ISSUE THREAD

**Issue by HikayatAyat** [ChestShop-authors/ChestShop-3#529]
### What is happening?

Currently using Advanced Towny plugin version  0.98.3.0 with Vault. We installed ChestShops and ChestShop - Towny https://dev.bukkit.org/projects/chestshop-towny

Steps that create the problem:

1. Chestshop-Towny configured that only shops can be made within shop plots.

2. Asked a player (mayor) to create a shop using sample lines given in front page of plugin. E.g:

Username
64
B 10 : 5 S
Dirt

3. Sign appears blank. However when OP makes sign, it works for them.

4. Asked the same player to do it. Still same error. Blank sign. There were no error messages mentioned in chat. 

5. Checked LuckPerms editor, gave default players the ability to create shops by giving the following node: 
ChestShop.shop.* 

Another node, chestshop.towny.bypass was set to false to ensure players do not build outside of shop plots set by town mayor. Also to prevent random shops being built outside of town claim areas.

6. Saved and updated LP. But the changes were not applied. Received following message in the log:
[03:15:47 INFO]: [LP] No changes were applied from the web editor, the returned data didn't contain any edits.

7. Repeated by inserted the ChestShop.shop* perm node into default players. Saved and applied edits. Same message received in no.6. Checked LP perms, the perm node is missing. 

### What did you expect to happen?

1. Players can create shops in designated shop plots set by the Town Mayor. 

2. Sign does not go blank when someone creates a shop on a plot designated as a shop. 

### Plugin Version

ChestShop 3.12.2

### Plugin Config

Please refer to link to see in full view: https://pastebin.com/TSCRdG4e

### Server Version

1.19

### Server Log

Below are some magnified instances where a player was asked to make a shop using the format provided in the front page of the plugin (as mentioned above)

1. https://pastebin.com/5WVx5f5Z (First attempt)

2. https://pastebin.com/7LekAHr0 (Second attempt)

2. https://pastebin.com/y6R4HyZ2  (Third Attempt)

In one attempt as OP, I was successful in making a shop. But when I asked the player to imitate the format and style, their shop could not be created and shows blank signs only.

1. https://pastebin.com/ZBYrLH5t (Successful attempt by Server OP)

Hope this suffices. Please let me know if you require more details.

### What other plugins are you running?

1. Towny 0.98.3.0
2. ChestShop - Towny  1.0.5 (build 17) 
3. ChestSort 13.3.0
4. Vault  1.7.3-b131
5. CMI version 9.2.2.0
6. CrazyCrates version 1.11.5-SNAPSHOT
7. EconomyShopGUI version 4.7.4
8. FlagWar version 0.5.2
9. CoreProtect version 21.2
10. TownyCombat version 0.3.0
11. AuctionHouse version 3.3.1
12. LuckPerms version 5.4.30

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
> - [x] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.

Please don't lie, you are running 3.12.2 which is not the latest build.

The issue you are describing is already fixed and is due to the username being specified on the first line (something that the instructions clearly state that you should not do, the latest build allows that though because for some reason people keep using it wrongly...)

**Comment by HikayatAyat** [comment]
Hi there, sorry for my oversight. May I confirm if the latest build is now  ChestShop version 3.12.3-SNAPSHOT (build 359) as of 30 July 2022?

The latest error we are not getting is "You are not allowed to create a shop here". Plugins are the same as above. Appreciate your guidance, thank you.

**Comment by Phoenix616** [comment]
> Hi there, sorry for my oversight. May I confirm if the latest build is now ChestShop version 3.12.3-SNAPSHOT (build 359) as of 30 July 2022? Have installed it recently.

That's indeed the latest build.

> The latest error we are now getting is "You are not allowed to create a shop here". Player is still unable to build in the set shop plot made by their town.

That means that the player trying to create the shop does not have the permission to create it at that location. E.g. because there is already a shop by another player found for the chest (if the `ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK` is disabled in the config), the chest is protected by someone else by an external, supported plugin like LWC, Lockette, etc., or it's inside a region that forbids/doesn't allow shops if you have something like WorldGuard support enabled in the config.

**Comment by HikayatAyat** [comment]
Hi there. While waiting for your reply I may have found an issue and hope to get your clarification.

Despite giving players the perms `ChestShop.shop.*` in LuckPerms, they were not able to create a shop. In addition, their chest was already placed a set plot shop by the mayor which they have permission to build on as mentioned above.

As I understand `ChestShop.shop.*`  
↓ (it grants people these nodes)
`ChestShop.shop.create` - lets you create shops
`ChestShop.shop.buy` - lets you buy from shops
`ChestShop.shop.sell -` lets you sell to shops

However, it wasn't until I inserted the three other nodes that they were finally able to build. Is there an error in  `ChestShop.shop.*`  or could it be something I overlooked?

Thank you

**Comment by Phoenix616** [comment]
Wildcard permissions only work if you haven't disabled them in LuckPerms. (Additionally you can disable default plugin permissions in LuckPerms. Seeing as you needed to grant permissions it sounds like you did that because ChestShop would work out of the box normally without any permission changes being required)
