### ISSUE TITLE
Block itens

### ISSUE THREAD

**Issue by felipeleite5w** [ChestShop-authors/ChestShop-3#530]
### What is happening?

how do i block certain itens to be sold? 

### What did you expect to happen?

I tried to use the plugin config but it didnt fina anything related

### Plugin Version

latest 1.7.10

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

1.7.10 

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

Vault, essentials

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
You use the [permission nodes](https://www.spigotmc.org/wiki/chestshop-permission-nodes/), not the config.
