### ISSUE TITLE
Problema no Bedrock

### ISSUE THREAD

**Issue by gleisonhr20** [ChestShop-authors/ChestShop-3#554]
### What is happening?

Olá, eu tou tendo problema para o ChestShop funcionar no Bedrock, já vi todas suas atualizações e forma de configurar, e não deu certo, é bem provável eu está fazendo errado, então venho pedir a ajuda de vocês, eu já vi as configurações que vocês falam para alterar, e já fiz isso varias vezes, e continua a msm coisa.

### What did you expect to happen?

Que eu conseguisse fazer funcionar, sem incomodar vocês.

### Plugin Version

3.12.2

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

1.19.40

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

Vault
Money

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
From what I could gather with a translator you are trying to get Bedrock accounts to work via Geyser? (I can't check that as you omitted the requested information of the log and config...) If so then please refer to the FAQ: https://www.spigotmc.org/wiki/chestshop-faq/#why-does-the-plugin-not-work-with-bedrock-players

On another note: Please try to keep things in English as this is an English project. Forcing everyone to run a translator is considered rude, might prevent people willing to help from being able to do so and also has the risk of you not being able to double check the translation.
