### ISSUE TITLE
Support Bedrock

### ISSUE THREAD

**Issue by gleisonhr20** [ChestShop-authors/ChestShop-3#555]
### What is happening?

Hello, I'm asking for support, because I've already looked at all your updates, and did as it was shown there, but it's still not working for me. The Bedrock support keeps showing "Your username is not a valid Minecraft username!" and I've already tried deleting and re-adding the plugin, but it keeps giving me the same error. Please help me fix this.

### What did you expect to happen?

support PaperMC

### Plugin Version

3.12.2

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

1.19.40

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

WorldGuard
WorldEdit
ViaVersion
Vault
SkinsRestorer
SepareWorldItems
RandomTP
Perms
MyHome
Multiverse-Core
McMoney
LandClaiming
HubThat
HolographicDisplays
GriefPreventionData
Geyser-Spigot
floodgate
CommandNPC
Citizens
![Screenshot_20230610_144959_Chrome](https://github.com/ChestShop-authors/ChestShop-3/assets/100954486/a2b44347-859e-4d20-a4d2-736f9e8afe7c)
![Screenshot_20230610_145020_Chrome](https://github.com/ChestShop-authors/ChestShop-3/assets/100954486/6d637b65-e8fc-4636-8b33-0b3c09de0229)
![Screenshot_20230610_134435_Minecraft](https://github.com/ChestShop-authors/ChestShop-3/assets/100954486/8a72f0df-6f03-408a-83b1-49931efb9b61)

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
Provide your full Geyser and Floodgate configs please (in text form, not screenshots...)
