### ISSUE TITLE
Problem with written books

### ISSUE THREAD

**Issue by JOO200** [ChestShop-authors/ChestShop-3#56]
If one tries to sell written books via ChestShop, are those being duplicated. A book will be transported in the inventory of a player while the book in the chest won't be removed. Thus books can be manifolded in ChestShops.

ChestShop version: 3.8.13-SNAPSHOT (build # 12)

**Comment by YellowZaki** [comment]
I can't reproduce this.

**Comment by JOO200** [comment]
I tested it on a local server too. Plugins only ChestShop, Vault and iConomy.

The bug is reproducible.

**Comment by Phoenix616** [comment]
I can't reproduce it either. Please provide some more info like the NBT of the book and your shop setup.

**Comment by JOO200** [comment]
Okay, i checked it today again.
The bug is only in the version 1.10.2 present. If you use the version 1.12 this issue will not appear.

That's weird. Sorry for the trouble...
