### ISSUE TITLE
Error on teleport (Folia)

### ISSUE THREAD

**Issue by DarkyG2** [ChestShop-authors/ChestShop-3#566]
### What is happening?

When I'm teleporting by using for example the plugin playerwarps I'm getting an error each time I teleport: https://pastebin.com/2kVnfjK2

### What did you expect to happen?

No errors

### Plugin Version

3.12.3-SNAPSHOT (build 393)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 full default config, never touched
 ```

</details>

### Server Version

This server is running Folia version git-Folia-"7299255" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7299255 on dev/optimisations) Error obtaining version information Previous version: git-Folia-"3b16d8f" (MC: 1.20.1)

### Server Log

<details>
  <summary>Log</summary>

  ```
 private (all errors are above)
  ```

</details>

### What other plugins are you running?

PlayerWarps, Placeholderapi, vault, EssentialsX, cmiLib, trademe, jobs reborn, FarmControl, FancyHolograms, FastAsyncWorldEdit, WorldGuard, Protocollib, ZNpcPlus, Lands

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

### Additional context

Error: https://pastebin.com/2kVnfjK2

**Comment by Phoenix616** [comment]
I'm unsure if this change really helps with your issue as Folia is all kinds of unstable right now but feel free to try and see if it solves it

**Comment by DarkyG2** [comment]
> I'm unsure if this change really helps with your issue as Folia is all kinds of unstable right now but feel free to try and see if it solves it

Issue has been fixed <3 Great job and thank you
