### ISSUE TITLE
Updating Item Metadata database to data version 3578 - Errors

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShop-3#569]
### What is happening?

Did a test run for 1.20.2 to check out the damage on various plugins, lo and behold, ChestShop go nuts lol.
https://gist.githubusercontent.com/andrewkm/97d01a23d35315eb9bde317a5d2f7e2b/raw/031072bc925e34dbc2cf960ea0028c417382f3b3/gistfile1.txt

Any ideas what could be happening here?

### What did you expect to happen?

Something more sane lol.

### Plugin Version

Compiled against https://github.com/ChestShop-authors/ChestShop-3/commit/53aa75d9b466a17b51837cf5f0bef7ddcf4f8b45

### Plugin Config

On Request.

### Server Version

Paper 1.20.2 Build 207

### Server Log

On Request.

### What other plugins are you running?

On Request.

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

### Additional context

On Request.

**Comment by andrewkm** [comment]
Getting a few other errors in console as well:

https://pastebin.com/raw/diV4fAna
https://pastebin.com/raw/WTxX90ct

**Comment by Phoenix616** [comment]
> https://gist.githubusercontent.com/andrewkm/97d01a23d35315eb9bde317a5d2f7e2b/raw/031072bc925e34dbc2cf960ea0028c417382f3b3/gistfile1.txt

You seem to have player skulls which are now considered invalid. Not sure if that is actually the case or just a bug in the server but realistically nothing ChestShop can do about and errors on item upgrades are kinda expected. Either re-create the the affected items or wait until there is a fix in the server (if that ever happens)

> Getting a few other errors in console as well:
> 
> https://pastebin.com/raw/diV4fAna  https://pastebin.com/raw/WTxX90ct

Different issue which should be in a different ticket and is happening due to an [SQLite driver update removing functionality](https://github.com/xerial/sqlite-jdbc/issues/963) without proper deprecation. Unfortunately the library used to access the databese has no fix for that yet. md might downgrade the driver though until it's clear that the driver continues to use that breaking behaviour so we will see. Otherwise I will have to find a workaround once 1.20.2 is considered stable.

**Comment by andrewkm** [comment]
Regarding player skulls, is this skulls found inside of chest-shop chests? Can I safely ignore these and simply tell players to remake their chest shops if they are experiencing issues with skulls inside them?

Regarding SQLite, I believe md_5 reverted it via https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-7491 now, so it should be fixed, will test shortly.

**Comment by Phoenix616** [comment]
Yeah, I discussed it with md to revert that until libraries had time to update and it was clear that the change was there to stick. We will most likely update that with 1.21.

As for the skulls issue: Yes, they would basically need to recreate the shops that rely on such skulls in order for the IDs still matching up with the item. I suspect that there is an actual bug with skulls though which could be fixed so if you can wait maybe do so until that is potentially fixed.

**Comment by andrewkm** [comment]
Can confirm the SQLite thing is fixed.

And yup, will wait, this is all just on my 1.20.2 test clone, that isn't yet in production. :)

**Comment by andrewkm** [comment]
> As for the skulls issue: Yes, they would basically need to recreate the shops that rely on such skulls in order for the IDs still matching up with the item. Nothing else should break due to that. I suspect that there is an actual bug with skulls though which could be fixed so if you can wait maybe do so until that is potentially fixed.

So decided to actually go ahead and run my update just moments ago.
Weirdly enough I didn't see the skull errors anymore.

Either something updated in Paper, or perhaps it was our HeadDatabase update but who knows.
I'll assume all is functional as it should be now and close out the ticket. :)
