### ISSUE TITLE
an internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by OMKOAKRE12** [ChestShop-authors/ChestShop-3#570]
### What is happening?

the plugin is not working

### What did you expect to happen?

idk

### Plugin Version

3.12.2 (build 353)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>
https://mclo.gs/WIdqmUX

### Server Version

paper 1.20.1

### Server Log

https://mclo.gs/WIdqmUX

### What other plugins are you running?

discordsrv
oneplayersleep 
set home
vienminer

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

### Additional context

pls answer as soon as posable

**Comment by Phoenix616** [comment]
Please read the log:

> [ChestShop] No Economy adapter found! You need to install either Vault or Reserve!

So just install Vault.
