### ISSUE TITLE
Version v3.9.0

### ISSUE THREAD

**Issue by felipeleite5w** [ChestShop-authors/ChestShop-3#572]
### What is happening?

Hello, sorry for opening an issue, but Im in 1.7.10 and I would like to know if version v3.9.0 works in this version. 

And how can I block an specific item to be sold? Example: allowing all itens to be sold but not diamond

### What did you expect to happen?

.

### Plugin Version

v3.9.0

### Plugin Config

.

### Server Version

1.7.10 

### Server Log

.

### What other plugins are you running?

Vault, essentials, griefprevention

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
Maybe? At least [the release](https://dev.bukkit.org/projects/chestshop/files/2518275) mentions 1.7.4. I suggest to just test it.

Generally speaking you are on your own though... that version is so extremely old that there is zero support for it. I would also appreciate if you wouldn't lie when creating issues or abusing the issue tracker for simple questions. There are support threads and a Discord for that.

**Comment by Phoenix616** [comment]
Yes, that can be done via permissions. See an overview of them [here](https://www.spigotmc.org/wiki/chestshop-permission-nodes/).
