### ISSUE TITLE
Cannot find how to create a chestshop

### ISSUE THREAD

**Issue by Alexidians** [ChestShop-authors/ChestShop-3#593]
### Is your feature request related to a problem? Please describe.

i didnt use the correct tag. but the problem is i dont know how to create chestshops. and cant find the way.

### Describe the solution you'd like

i cannot find the command to create chests. maybe try making a command wiki

### Describe alternatives you've considered

non

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

### Additional context

can you just tell me how to create a chestshop.

**Comment by Phoenix616** [comment]
There is no command, you just write the sign like this: https://hangar.papermc.io/ChestShop/ChestShop#how-to-create-a-player-shop (it's explained on the plugin page on all platforms ;))
