### ISSUE TITLE
Build 17 makes buying from adminshops not work.  

### ISSUE THREAD

**Issue by Momshroom** [ChestShop-authors/ChestShop-3#60]
Spigot 1.12
Adminshops worked in build 12, updating to build 17 breaks them.  I reverted to 12 and it works.  I haven't tried builds in between.
No errors on console.

**Comment by Momshroom** [comment]
I just tried builds 18 (which says it fixes this) and 19, and it still doesn't work for me.  Build 12 does.

**Comment by Phoenix616** [comment]
They work for me now. Please provide some more information about your shop setup, your config and your log.

**Comment by Momshroom** [comment]
**Our system:**
This server is running CraftBukkit version git-Spigot-7228328-d603539 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Vault
Craftconomy3 dev build
a whole lot of other stuff….

Chestshop config file: https://pastebin.com/s8EYfjiz

My test sign: http://prntscr.com/frb0z7

Regular, non-Admin, shops work in both versions.



**With Chestshop build 12: (Working)**

On boot up get this error:
https://pastebin.com/tJ7HafqT

when logging in, get this error:
https://pastebin.com/jTBy7p2p


When buying, it WORKS, and get this:
[19:48:04] [Craft Scheduler Thread - 16/INFO]: [ChestShop] Momshroom bought 1 Stone for 5.00 from Admin Shop at [Market] 86, 67, -17



**With build 19:**

On bootup:
https://pastebin.com/2jEu6nRS

On login:
NO ERROR

On admin shop use: 
doesn’t work.  no error.  nothing.


Please let me know what else you need or would like me to try.

**Comment by Phoenix616** [comment]
> Chestshop config file: https://pastebin.com/s8EYfjiz
> 
> My test sign: http://prntscr.com/frb0z7

You are using `AdminShop` on the sign but have `Admin Shop` (with a space) in your config? This is most likely what breaks them.

> **With Chestshop build 12: (Working)**
> 
> On boot up get this error:
> https://pastebin.com/tJ7HafqT
> 
> when logging in, get this error:
> https://pastebin.com/jTBy7p2p
> 
> When buying, it WORKS, and get this:
> [19:48:04] [Craft Scheduler Thread - 16/INFO]: [ChestShop] Momshroom bought 1 Stone for 5.00 from Admin Shop at [Market] 86, 67, -17

This results in you using the v3 users.db with a plugin expecting the old v2 format.

> With build 19:
> 
> On bootup:
> https://pastebin.com/2jEu6nRS

These are just some info messages by ORMLite.

**Comment by Momshroom** [comment]
Oddly enough, changing the config had no effect, BUT redoing the signs to Admin Shop, with the space, made them work in build 19 (Even with the config changed to without the space!!).  Both ways work in build 12. Changing the config to other names will let me create the signs, but not buy from them, but Admin Shop does work, regardless.

Thank you, I guess I just need to redo a lot of signs for the update to work.

**Comment by Phoenix616** [comment]
Really strange that it isn't working even after changing the config entry. If you just reloaded it via the plugin's command I suggest that you try restarting the server. That setting is (currently) not properly applied when reloading.

**Comment by Momshroom** [comment]
Yes, restarting it with the new config fixes it.  Tyvm.  Sorry for the slow response.
