### ISSUE TITLE
Currency-Symbol change?

### ISSUE THREAD

**Issue by Pyario** [ChestShop-authors/ChestShop-3#603]
### What is happening?

I can't find a way to change the currency symbol in the config/messages! Isn't there one or is it hardcoded depending on the language type? I use the German language and don't want to have "Eurs" but rather Gems because that's my currency or the name...

### What did you expect to happen?

searched all the configs and found nothing!

### Plugin Version

3.12.3-Snapshot (build 421)

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
 [Put the config here]
 ```

</details>

### Server Version

1.21

### Server Log

<details>
  <summary>Log</summary>

  ```
  [Your log here]
  ```

</details>

### What other plugins are you running?

![Screenshot 2024-07-19 150658](https://github.com/user-attachments/assets/6d2c05df-93c4-4ce5-bc3c-e8e9ad4047ca)

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

**Comment by Phoenix616** [comment]
The currency symbol that is used in messages is set via your economy plugin. ChestShop just reads that value via Vault so you have to change it in its config.
