### ISSUE TITLE
1.21.x Support?

### ISSUE THREAD

**Issue by BenTheMan69** [ChestShop-authors/ChestShop-3#615]
### Is your feature request related to a problem? Please describe.

There hasnt been a development build since August and i am wondering is this plugin is still being developed since i would like to use it on my new server.

### Describe the solution you'd like

please update the plugin to 1.21.x or tell us if this plugin has been discontinued

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I have checked that the latest build doesn't already implement the feature.

**Comment by Phoenix616** [comment]
Do you have a specific issue with the latest build that would require fixing? I have been using them on 1.21.x just fine and am in the process of testing 1.21.4.

**Comment by BenTheMan69** [comment]
Yes. The plugin doesnt work for me in 1.21.4 if you want i can send the console logs right now

**Comment by Phoenix616** [comment]
> Yes. The plugin doesnt work for me in 1.21.4 if you want i can send the console logs right now

Well ideally you should open a bug report as that asks for all required info.

**Comment by BenTheMan69** [comment]
> > Yes. The plugin doesnt work for me in 1.21.4 if you want i can send the console logs right now
> 
> Well ideally you should open a bug report as that asks for all required info.

I will do that. Thanks!

**Comment by BenTheMan69** [comment]
#616
