### ISSUE TITLE
More possibilities for chestshops

### ISSUE THREAD

**Issue by Sprungente** [ChestShop-authors/ChestShop-3#62]
Hello everyone

I have a question from my community

some people from my servernetwork wanna use sell/buy enchanted books, spawnereggs ans some other stuff that has included nbt-changes in shops. 

Could you implement features that player could buy/sell Items with nbtmodifications?

**Comment by Phoenix616** [comment]
Please provide some more details about the items that aren't working as all Enchanted Books, Spawn Eggs, Potions etc. are currently supported and working.

**Comment by Phoenix616** [comment]
No more information provided. Closing this as items with NBT seem to work correctly in the latest versions.
