### ISSUE TITLE
Reloading/Starting-up-Issue

### ISSUE THREAD

**Issue by MineTim** [ChestShop-authors/ChestShop-3#66]
That's the text in the console - I am using ChestShop under Linux. (It's a BungeeCord-server!)

https://pastebin.com/B4KE80iS

Greetings
Minecraft_Tim

**Comment by Phoenix616** [comment]
These are only warnings and not errors. See [issue 1073](https://dev.bukkit.org/projects/chestshop/issues/1073) on dev bukkit.
