### ISSUE TITLE
Cannot work when I click the sign

### ISSUE THREAD

**Issue by noy98** [ChestShop-authors/ChestShop-3#71]
I registered an item clearly with this plugin.

but click is not working

No movement when I click the sign to buy or sell

**Comment by Phoenix616** [comment]
Make sure that you have the permissions to use shop signs and that the plugin enabled correctly. Also make sure that you aren't in creative mode while having creative players disabled.

If you are sure that all the above is setup correctly then please provide some information about your issue like the shop sign that you are using, the plugin version, your server version and your server log. Without that one cannot debug such problems.

**Comment by Phoenix616** [comment]
No response providing additional information. Assume that it is not an issue anymore.
