### ISSUE TITLE
How to setup Xerial SQLite Driver?

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#84]
I see this erros on log:
`[00:52:04] [Server thread/ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
`

How to setup Xerial SQLite Driver?

**Comment by Phoenix616** [comment]
Duplicate of #49
