### ISSUE TITLE
Is there anywhere a guide how to trade?

### ISSUE THREAD

**Issue by DmitryRendov** [ChestShop-authors/ChestShop-3#86]
*Not an issue - just request for help and stuff for search engines like google.*
It's still the challenge to sell/buy enchanted things, books via the plugin.
Thank you!

**Comment by Phoenix616** [comment]
The Bukkit dev project page contains[ a section](https://dev.bukkit.org/projects/chestshop?gameCategorySlug=bukkit-plugins&projectID=31263#title-1-2) on how to setup signs.
