### ISSUE TITLE
Feature Request: Full Inventory to Buy Up To Free Inventory Space

### ISSUE THREAD

**Issue by TheDGOfficial** [ChestShop-authors/ChestShop-3#88]
Example:

AdminShop
2305
B FREE
Iron Ingot

I rightclick with empty inventory and sends the "full inventory" error.
I want to buy up to free inventory space, buy 2304 iron ingots. Like selling.

**Comment by Phoenix616** [comment]
Yeah that would make sense, I kinda assumed that the `ALLOW_PARTIAL_TRANSACTIONS` setting already handled that. Gonna look into that.

**Comment by TheDGOfficial** [comment]
`ALLOW_PARTIAL_TRANSACTIONS` is already enabled in my config.

**Comment by TheDGOfficial** [comment]
?

**Comment by Phoenix616** [comment]
Is there really a need for single letter comments? As it stands now this is not supported and an enhancement that might be implemented in the future.

**Comment by TheDGOfficial** [comment]
Thanks for reply. I'm really need this update for my server. I'm waiting for update.
