### ISSUE TITLE
Buing and selling is not work

### ISSUE THREAD

**Issue by 100petr** [ChestShop-authors/ChestShop-3#89]
#### Plugin Version
3.8.13-SNAPSHOT (build #41)
 
#### Plugin Config
https://pastebin.com/28rauGhZ
 
#### Server Version
Spigot 1.12.2
Build 201712170430, development
(lasted version)

#### Server Log
https://pastebin.com/Yx0AvzeW

#### What other plugins are you running?
https://image.prntscr.com/image/YMnFx-CYRYOY35G6Ec8d7g.png

#### What is happening?
Buing and selling items is not work..  proof: https://youtu.be/MENhTg4zv3M

**Comment by Phoenix616** [comment]
You have set the admin shop name to "Admin Shop" in your config but it is "AdminShop" on the sign. Set the config setting to "AdminShop" to see if that caused your issue.

**Comment by 100petr** [comment]
It always worked this way .. And it write: "The shop was created"

**Comment by Phoenix616** [comment]
Well does it work if you change the config setting? And that it ignores the space shouldn't be happening and is not intended behaviour.

**Comment by 100petr** [comment]
Interesting, you are right. Thanks.
