### ISSUE TITLE
iteminfo isn't working properly in case of enchanted things, books

### ISSUE THREAD

**Issue by DmitryRendov** [ChestShop-authors/ChestShop-3#90]
Guys, how can I trade enchanted books?

#### Plugin Version
3.8.13-SNAPSHOT build 39
 
#### Plugin Config
N/A
 
#### Server Version
latest Spigot 1.12.2
 
#### Server Log
[The full latest.log file]

#### What other plugins are you running?
Vault

#### What is happening?
/iteminfo is useless in case of enchanted books - I have 403#1,2,3... for many diff books

#### What did you expect to happen?
Proper enchanted books code

Please provide any additional info below

**Comment by Phoenix616** [comment]
This is the correct output. The plugin stores the item in an SQLite database and appends the unique id behind the # because enchanted books itself do not have damage values. (Damage values get removed in 1.13 anyways so this id system will be used for all items with extra data)
