### ISSUE TITLE
[bug] players need to wait long to join the server?

### ISSUE THREAD

**Issue by TwanLuttik** [ChestShop-authors/ChestShop-3#96]
when i install this plugin eveertyhing working fine but after a week when players try to connect its taken really long and i found out its the chestshop plugin and really use the chestshop plugin.

**Your server log**
no error's in the server log

**The configuration of the plugin**
default config settings, never changed

**Your server version**
running on the latest spigot version

**Timings**
https://www.spigotmc.org/go/timings?url=remiyiduku

**plugins**
askyblock
auctionhouse
buycraft
chatcontrol
chestshop
citzens
clearlag
commandNPC
cratplus
essentialsChat
essentialsX
FastAsyncVoxelSniper-favs
FastAsyncWorldEdit-bukkit
featherboard
holograms
hologramsPlaceholders
leaderheads
limitcrafting
mcMMO
mobstacker2
Multiverse-Core
MVdWPlaceholderAPI
permissionsEx
OreGenReloaded
permissionsEx
perworldinventory
placeholderAPI
playervaults
protocolLib
Silkspwners
stablist
supertrails
switch
timeismoney
vault
votifier
votingplugin
voxelsniper
worldedit
worldguard
worldguardextraflagsplugin

**Comment by Phoenix616** [comment]
Please provide some more information like
- Your server version
- Your server log
- The version of the plugin that you are running
- The configuration of the plugin
- The other plugins that you are running
- How you detected that it was ChestShop
- Your timings
- The amount of players that you had (ideally by directly providing the users.db file)

**Comment by TwanLuttik** [comment]
i updated the list @Phoenix616

**Comment by Phoenix616** [comment]
Please also provide a timings report for when the issue occurs and the exact server and plugin version. (or your server log as that already contains the version information)

**Comment by TwanLuttik** [comment]
i posted the timings @Phoenix616

**Comment by Phoenix616** [comment]
There is no indication that ChestShop is the plugin responsible for your login issues. (the only thing ChestShop does on login is save the player's current name but that's done in an async thread)

Your timings in general seem pretty good, the plugins that seems to lag on join are ASkyBlock, Join, Essentials and FeatherBoard.

How exactly did you determinate that ChestShop was the cause?

**Comment by TwanLuttik** [comment]
i was running my skyblock server with some players and after a few days, when i logging into the server it was taking so long to login so i was searching out each plugin and test 1 of the 40 plugins and when i remove the chestshop plugin than it was gone but its when i'm putting the plugin into the server the problem seems to be fixed, but now i updated my server again and the issue is back again, so i'm don;t how to fix this, and i reported the timings of ASkyBlock.

**Comment by TwanLuttik** [comment]
@Phoenix616 I want to apologize because, my spawn had a corrupted file so that was the reason and not your plugin.
