### ISSUE TITLE
Shop sign selects wrong chest

### ISSUE THREAD

**Issue by Fridgey** [ChestShop-authors/ChestShop-3#97]
#### Plugin Version
 ChestShop version 3.8.13-SNAPSHOT (compiled at 2017-12-30T23:19:24Z)
#### Plugin Config
 https://hastebin.com/nakobohuze.bash
#### Server Version
 This server is running CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
#### What is happening?
When a player right clicks on a chest to place a chest shop sign and types "?" on the bottom line, the plugin pulls from the chest next to the sign instead of the chest it is attached to.
As you can see here, he placed the left sign and it pulled from the chest to the right:
![Image 1](https://i.imgur.com/9Rhy85h.png)
Inventory of the chest on the right:
![Image 2](https://i.imgur.com/0Wa5oML.png)
Inventory of the chest on the left:
![Image 3](https://i.imgur.com/H4E3eXg.png)

Also! It seems the sign is actually trying to sell what is from the right chest instead of the left chest!
I tested by making the player write "rabbit foot" on the sign instead of a "?" and it put "Rabbit Foot". However, the shop says it is out of stock. I then placed one rabbit foot in side the right chest and I bought it. Hope this is all the info you need, please ask me if you need anything else. And thanks for supporting this plugin! :)
#### What did you expect to happen?
I expected the sign on the left to say "Rabbit Foot", instead of "Ghast Tear", since that is what is in the chest.

**Comment by Phoenix616** [comment]
This is due to the algorithm that selects the shop chest from the sign, it currently doesn't take the orientation of the sign into account. I'll look into changing that.

**Comment by Phoenix616** [comment]
Should be fixed in [build 57](https://ci.minebench.de/job/ChestShop-3/57/).
